package main

type Action struct {
	Id            int
	AcceptableStr []string
}

type Room struct {
	Id         int
	ShortDesc  string
	LongDesc   string
	Connection map[int]int // map[action]room
}

var Actions = make(map[int]*Action)
var Rooms = make(map[int]*Room)
var Msgs = make(map[int]string)

func LoadAdventure() {
	LoadRooms()
	LoadActions()
	LoadMessages()
	LoadObjects()
	LoadShortDesc()
	LoadLongDesc()
	LoadTravel()
	LoadObjectLoc()
}

func LoadRooms() {
	for i := 1; i <= 140; i++ {
		Rooms[i] = &Room{}
		Rooms[i].Connection = make(map[int]int)
	}
}

func LoadLongDesc() {
	// verbose room descriptions
	Rooms[1].LongDesc = `YOU ARE STANDING AT THE END OF A ROAD BEFORE A SMALL BRICK BUILDING. AROUND YOU IS A FOREST. A SMALL STREAM FLOWS OUT OF THE BUILDING AND DOWN A GULLY.`
	Rooms[2].LongDesc = `YOU HAVE WALKED UP A HILL, STILL IN THE FOREST. THE ROAD SLOPES BACK DOWN THE OTHER SIDE OF THE HILL. THERE IS A BUILDING IN THE DISTANCE.`
	Rooms[3].LongDesc = `YOU ARE INSIDE A BUILDING, A WELL HOUSE FOR A LARGE SPRING.`
	Rooms[4].LongDesc = `YOU ARE IN A VALLEY IN THE FOREST BESIDE A STREAM TUMBLING ALONG A ROCKY BED.`
	Rooms[5].LongDesc = `YOU ARE IN OPEN FOREST, WITH A DEEP VALLEY TO ONE SIDE.`
	Rooms[6].LongDesc = `YOU ARE IN OPEN FOREST NEAR BOTH A VALLEY AND A ROAD.`
	Rooms[7].LongDesc = `AT YOUR FEET ALL THE WATER OF THE STREAM SPLASHES INTO A 2-INCH SLIT IN THE ROCK. DOWNSTREAM THE STREAMBED IS BARE ROCK.`
	Rooms[8].LongDesc = `YOU ARE IN A 20-FOOT DEPRESSION FLOORED WITH BARE DIRT. SET INTO THE DIRT IS A STRONG STEEL GRATE MOUNTED IN CONCRETE. A DRY STREAMBED LEADS INTO THE DEPRESSION.`
	Rooms[9].LongDesc = `YOU ARE IN A SMALL CHAMBER BENEATH A 3X3 STEEL GRATE TO THE SURFACE. A LOW CRAWL OVER COBBLES LEADS INWARD TO THE WEST.`
	Rooms[10].LongDesc = `YOU ARE CRAWLING OVER COBBLES IN A LOW PASSAGE. THERE IS A DIM LIGHT AT THE EAST END OF THE PASSAGE.`
	Rooms[11].LongDesc = `YOU ARE IN A DEBRIS ROOM FILLED WITH STUFF WASHED IN FROM THE SURFACE. A LOW WIDE PASSAGE WITH COBBLES BECOMES PLUGGED WITH MUD AND DEBRIS HERE, BUT AN AWKWARD CANYON LEADS UPWARD AND WEST. A NOTE ON THE WALL SAYS "MAGIC WORD XYZZY".`
	Rooms[12].LongDesc = `YOU ARE IN AN AWKWARD SLOPING EAST/WEST CANYON.`
	Rooms[13].LongDesc = `YOU ARE IN A SPLENDID CHAMBER THIRTY FEET HIGH. THE WALLS ARE FROZEN RIVERS OF ORANGE STONE. AN AWKWARD CANYON AND A GOOD PASSAGE EXIT FROM EAST AND WEST SIDES OF THE CHAMBER.`
	Rooms[14].LongDesc = `AT YOUR FEET IS A SMALL PIT BREATHING TRACES OF WHITE MIST. AN EAST PASSAGE ENDS HERE EXCEPT FOR A SMALL CRACK LEADING ON.`
	Rooms[15].LongDesc = `YOU ARE AT ONE END OF A VAST HALL STRETCHING FORWARD OUT OF SIGHT TO THE WEST. THERE ARE OPENINGS TO EITHER SIDE. NEARBY, A WIDE STONE STAIRCASE LEADS DOWNWARD. THE HALL IS FILLED WITH WISPS OF WHITE MIST SWAYING TO AND FRO ALMOST AS IF ALIVE. A COLD WIND BLOWS UP THE STAIRCASE. THERE IS A PASSAGE AT THE TOP OF A DOME BEHIND YOU.`
	Rooms[16].LongDesc = `THE CRACK IS FAR TOO SMALL FOR YOU TO FOLLOW.`
	Rooms[17].LongDesc = `YOU ARE ON THE EAST BANK OF A FISSURE SLICING CLEAR ACROSS THE HALL. THE MIST IS QUITE THICK HERE, AND THE FISSURE IS TOO WIDE TO JUMP.`
	Rooms[18].LongDesc = `THIS IS A LOW ROOM WITH A CRUDE NOTE ON THE WALL. THE NOTE SAYS, "YOU WON'T GET IT UP THE STEPS".`
	Rooms[19].LongDesc = `YOU ARE IN THE HALL OF THE MOUNTAIN KING, WITH PASSAGES OFF IN ALL DIRECTIONS.`
	Rooms[20].LongDesc = `YOU ARE AT THE BOTTOM OF THE PIT WITH A BROKEN NECK.`
	Rooms[21].LongDesc = `YOU DIDN'T MAKE IT.`
	Rooms[22].LongDesc = `THE DOME IS UNCLIMBABLE.`
	Rooms[23].LongDesc = `YOU ARE AT THE WEST END OF THE TWOPIT ROOM. THERE IS A LARGE HOLE IN THE WALL ABOVE THE PIT AT THIS END OF THE ROOM.`
	Rooms[24].LongDesc = `YOU ARE AT THE BOTTOM OF THE EASTERN PIT IN THE TWOPIT ROOM. THERE IS A SMALL POOL OF OIL IN ONE CORNER OF THE PIT.`
	Rooms[25].LongDesc = `YOU ARE AT THE BOTTOM OF THE WESTERN PIT IN THE TWOPIT ROOM. THERE IS A LARGE HOLE IN THE WALL ABOUT 25 FEET ABOVE YOU.`
	Rooms[26].LongDesc = `YOU CLAMBER UP THE PLANT AND SCURRY THROUGH THE HOLE AT THE TOP.`
	Rooms[27].LongDesc = `YOU ARE ON THE WEST SIDE OF THE FISSURE IN THE HALL OF MISTS.`
	Rooms[28].LongDesc = `YOU ARE IN A LOW N/S PASSAGE AT A HOLE IN THE FLOOR. THE HOLE GOES DOWN TO AN E/W PASSAGE.`
	Rooms[29].LongDesc = `YOU ARE IN THE SOUTH SIDE CHAMBER.`
	Rooms[30].LongDesc = `YOU ARE IN THE WEST SIDE CHAMBER OF THE HALL OF THE MOUNTAIN KING. A PASSAGE CONTINUES WEST AND UP HERE.`
	Rooms[31].LongDesc = `>$<`
	Rooms[32].LongDesc = `YOU CAN'T GET BY THE SNAKE.`
	Rooms[33].LongDesc = `YOU ARE IN A LARGE ROOM, WITH A PASSAGE TO THE SOUTH, A PASSAGE TO THE WEST, AND A WALL OF BROKEN ROCK TO THE EAST. THERE IS A LARGE "Y2" ON A ROCK IN THE ROOM'S CENTER.'`
	Rooms[34].LongDesc = `YOU ARE IN A JUMBLE OF ROCK, WITH CRACKS EVERYWHERE.`
	Rooms[35].LongDesc = `YOU'RE AT A LOW WINDOW OVERLOOKING A HUGE PIT, WHICH EXTENDS UP OUT OF SIGHT. A FLOOR IS INDISTINCTLY VISIBLE OVER 50 FEET BELOW. TRACES OF WHITE MIST COVER THE FLOOR OF THE PIT, BECOMING THICKER TO THE RIGHT. MARKS IN THE DUST AROUND THE WINDOW WOULD SEEM TO INDICATE THAT SOMEONE HAS BEEN HERE RECENTLY. DIRECTLY ACROSS THE PIT FROM YOU AND 25 FEET AWAY THERE IS A SIMILAR WINDOW LOOKING INTO A LIGHTED ROOM. A SHADOWY FIGURE CAN BE SEEN THERE PEERING BACK AT YOU.`
	Rooms[36].LongDesc = `YOU ARE IN A DIRTY BROKEN PASSAGE. TO THE EAST IS A CRAWL. TO THE WEST IS A LARGE PASSAGE. ABOVE YOU IS A HOLE TO ANOTHER PASSAGE.`
	Rooms[37].LongDesc = `YOU ARE ON THE BRINK OF A SMALL CLEAN CLIMBABLE PIT. A CRAWL LEADS WEST.`
	Rooms[38].LongDesc = `YOU ARE IN THE BOTTOM OF A SMALL PIT WITH A LITTLE STREAM, WHICH ENTERS AND EXITS THROUGH TINY SLITS.`
	Rooms[39].LongDesc = `YOU ARE IN A LARGE ROOM FULL OF DUSTY ROCKS. THERE IS A BIG HOLE IN THE FLOOR. THERE ARE CRACKS EVERYWHERE, AND A PASSAGE LEADING EAST.`
	Rooms[40].LongDesc = `YOU HAVE CRAWLED THROUGH A VERY LOW WIDE PASSAGE PARALLEL TO AND NORTH OF THE HALL OF MISTS.`
	Rooms[41].LongDesc = `YOU ARE AT THE WEST END OF HALL OF MISTS. A LOW WIDE CRAWL CONTINUES WEST AND ANOTHER GOES NORTH. TO THE SOUTH IS A LITTLE PASSAGE 6 FEET OFF THE FLOOR.`
	Rooms[42].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[43].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[44].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[45].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[46].LongDesc = `DEAD END`
	Rooms[47].LongDesc = `DEAD END`
	Rooms[48].LongDesc = `DEAD END`
	Rooms[49].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[50].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[51].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[52].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[53].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[54].LongDesc = `DEAD END`
	Rooms[55].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[56].LongDesc = `DEAD END`
	Rooms[57].LongDesc = `YOU ARE ON THE BRINK OF A THIRTY FOOT PIT WITH A MASSIVE ORANGE COLUMN DOWN ONE WALL. YOU COULD CLIMB DOWN HERE BUT YOU COULD NOT GET BACK UP. THE MAZE CONTINUES AT THIS LEVEL.`
	Rooms[58].LongDesc = `DEAD END`
	Rooms[59].LongDesc = `YOU HAVE CRAWLED THROUGH A VERY LOW WIDE PASSAGE PARALLEL TO AND NORTH OF THE HALL OF MISTS.`
	Rooms[60].LongDesc = `YOU ARE AT THE EAST END OF A VERY LONG HALL APPARENTLY WITHOUT SIDE CHAMBERS. TO THE EAST A LOW WIDE CRAWL SLANTS UP. TO THE NORTH A ROUND TWO FOOT HOLE SLANTS DOWN.`
	Rooms[61].LongDesc = `YOU ARE AT THE WEST END OF A VERY LONG FEATURELESS HALL. THE HALL JOINS UP WITH A NARROW NORTH/SOUTH PASSAGE.`
	Rooms[62].LongDesc = `YOU ARE AT A CROSSOVER OF A HIGH N/S PASSAGE AND A LOW E/W ONE.`
	Rooms[63].LongDesc = `DEAD END`
	Rooms[64].LongDesc = `YOU ARE AT A COMPLEX JUNCTION. A LOW HANDS AND KNEES PASSAGE FROM THE NORTH JOINS A HIGHER CRAWL FROM THE EAST TO MAKE A WALKING PASSAGE GOING WEST. THERE IS ALSO A LARGE ROOM ABOVE. THE AIR IS DAMP HERE.`
	Rooms[65].LongDesc = `YOU ARE IN BEDQUILT, A LONG EAST/WEST PASSAGE WITH HOLES EVERYWHERE. TO EXPLORE AT RANDOM SELECT NORTH, SOUTH, UP, OR DOWN.`
	Rooms[66].LongDesc = `YOU ARE IN A ROOM WHOSE WALLS RESEMBLE SWISS CHEESE. OBVIOUS PASSAGES GO WEST, EAST, NE, AND NW. PART OF THE ROOM IS OCCUPIED BY A LARGE BEDROCK BLOCK.`
	Rooms[67].LongDesc = `YOU ARE AT THE EAST END OF THE TWOPIT ROOM. THE FLOOR HERE IS LITTERED WITH THIN ROCK SLABS, WHICH MAKE IT EASY TO DESCEND THE PITS. THERE IS A PATH HERE BYPASSING THE PITS TO CONNECT PASSAGES FROM EAST AND WEST. THERE ARE HOLES ALL OVER, BUT THE ONLY BIG ONE IS ON THE WALL DIRECTLY OVER THE WEST PIT WHERE YOU CAN'T GET TO IT.`
	Rooms[68].LongDesc = `YOU ARE IN A LARGE LOW CIRCULAR CHAMBER WHOSE FLOOR IS AN IMMENSE SLAB FALLEN FROM THE CEILING (SLAB ROOM). EAST AND WEST THERE ONCE WERE LARGE PASSAGES, BUT THEY ARE NOW FILLED WITH BOULDERS. LOW SMALL PASSAGES GO NORTH AND SOUTH, AND THE SOUTH ONE QUICKLY BENDS WEST AROUND THE BOULDERS.`
	Rooms[69].LongDesc = `YOU ARE IN A SECRET N/S CANYON ABOVE A LARGE ROOM.`
	Rooms[70].LongDesc = `YOU ARE IN A SECRET N/S CANYON ABOVE A SIZABLE PASSAGE.`
	Rooms[71].LongDesc = `YOU ARE IN A SECRET CANYON AT A JUNCTION OF THREE CANYONS, BEARING NORTH, SOUTH, AND SE. THE NORTH ONE IS AS TALL AS THE OTHER TWO COMBINED.`
	Rooms[72].LongDesc = `YOU ARE IN A LARGE LOW ROOM. CRAWLS LEAD NORTH, SE, AND SW.`
	Rooms[73].LongDesc = `DEAD END CRAWL.`
	Rooms[74].LongDesc = `YOU ARE IN A SECRET CANYON WHICH HERE RUNS E/W. IT CROSSES OVER A VERY TIGHT CANYON 15 FEET BELOW. IF YOU GO DOWN YOU MAY NOT BE ABLE TO GET BACK UP.`
	Rooms[75].LongDesc = `YOU ARE AT A WIDE PLACE IN A VERY TIGHT N/S CANYON.`
	Rooms[76].LongDesc = `THE CANYON HERE BECOMES TOO TIGHT TO GO FURTHER SOUTH.`
	Rooms[77].LongDesc = `YOU ARE IN A TALL E/W CANYON. A LOW TIGHT CRAWL GOES 3 FEET NORTH AND SEEMS TO OPEN UP.`
	Rooms[78].LongDesc = `THE CANYON RUNS INTO A MASS OF BOULDERS -- DEAD END.`
	Rooms[79].LongDesc = `THE STREAM FLOWS OUT THROUGH A PAIR OF 1 FOOT DIAMETER SEWER PIPES. IT WOULD BE ADVISABLE TO USE THE EXIT.`
	Rooms[80].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[81].LongDesc = `DEAD END`
	Rooms[82].LongDesc = `DEAD END`
	Rooms[83].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[84].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[85].LongDesc = `DEAD END`
	Rooms[86].LongDesc = `DEAD END`
	Rooms[87].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE.`
	Rooms[88].LongDesc = `YOU ARE IN A LONG, NARROW CORRIDOR STRETCHING OUT OF SIGHT TO THE WEST. AT THE EASTERN END IS A HOLE THROUGH WHICH YOU CAN SEE A PROFUSION OF LEAVES.`
	Rooms[89].LongDesc = `THERE IS NOTHING HERE TO CLIMB. USE "UP" OR "OUT" TO LEAVE THE PIT.`
	Rooms[90].LongDesc = `YOU HAVE CLIMBED UP THE PLANT AND OUT OF THE PIT.`
	Rooms[91].LongDesc = `YOU ARE AT THE TOP OF A STEEP INCLINE ABOVE A LARGE ROOM. YOU COULD CLIMB DOWN HERE, BUT YOU WOULD NOT BE ABLE TO CLIMB UP. THERE IS A PASSAGE LEADING BACK TO THE NORTH.`
	Rooms[92].LongDesc = `YOU ARE IN THE GIANT ROOM. THE CEILING HERE IS TOO HIGH UP FOR YOUR LAMP TO SHOW IT. CAVERNOUS PASSAGES LEAD EAST, NORTH, AND SOUTH. ON THE WEST WALL IS SCRAWLED THE INSCRIPTION, "FEE FIE FOE FOO" [SIC].`
	Rooms[93].LongDesc = `THE PASSAGE HERE IS BLOCKED BY A RECENT CAVE-IN.`
	Rooms[94].LongDesc = `YOU ARE AT ONE END OF AN IMMENSE NORTH/SOUTH PASSAGE.`
	Rooms[95].LongDesc = `YOU ARE IN A MAGNIFICENT CAVERN WITH A RUSHING STREAM, WHICH CASCADES OVER A SPARKLING WATERFALL INTO A ROARING WHIRLPOOL WHICH DISAPPEARS THROUGH A HOLE IN THE FLOOR. PASSAGES EXIT TO THE SOUTH AND WEST.`
	Rooms[96].LongDesc = `YOU ARE IN THE SOFT ROOM. THE WALLS ARE COVERED WITH HEAVY CURTAINS, THE FLOOR WITH A THICK PILE CARPET. MOSS COVERS THE CEILING.`
	Rooms[97].LongDesc = `THIS IS THE ORIENTAL ROOM. ANCIENT ORIENTAL CAVE DRAWINGS COVER THE WALLS. A GENTLY SLOPING PASSAGE LEADS UPWARD TO THE NORTH, ANOTHER PASSAGE LEADS SE, AND A HANDS AND KNEES CRAWL LEADS WEST.`
	Rooms[98].LongDesc = `YOU ARE FOLLOWING A WIDE PATH AROUND THE OUTER EDGE OF A LARGE CAVERN. FAR BELOW, THROUGH A HEAVY WHITE MIST, STRANGE SPLASHING NOISES CAN BE HEARD. THE MIST RISES UP THROUGH A FISSURE IN THE CEILING. THE PATH EXITS TO THE SOUTH AND WEST.`
	Rooms[99].LongDesc = `YOU ARE IN AN ALCOVE. A SMALL NW PATH SEEMS TO WIDEN AFTER A SHORT DISTANCE. AN EXTREMELY TIGHT TUNNEL LEADS EAST. IT LOOKS LIKE A VERY TIGHT SQUEEZE. AN EERIE LIGHT CAN BE SEEN AT THE OTHER END.`
	Rooms[100].LongDesc = `YOU'RE IN A SMALL CHAMBER LIT BY AN EERIE GREEN LIGHT. AN EXTREMELY NARROW TUNNEL EXITS TO THE WEST. A DARK CORRIDOR LEADS NE.`
	Rooms[101].LongDesc = `YOU'RE IN THE DARK-ROOM. A CORRIDOR LEADING SOUTH IS THE ONLY EXIT.`
	Rooms[102].LongDesc = `YOU ARE IN AN ARCHED HALL. A CORAL PASSAGE ONCE CONTINUED UP AND EAST FROM HERE, BUT IS NOW BLOCKED BY DEBRIS. THE AIR SMELLS OF SEA WATER.`
	Rooms[103].LongDesc = `YOU'RE IN A LARGE ROOM CARVED OUT OF SEDIMENTARY ROCK. THE FLOOR AND WALLS ARE LITTERED WITH BITS OF SHELLS IMBEDDED IN THE STONE. A SHALLOW PASSAGE PROCEEDS DOWNWARD, AND A SOMEWHAT STEEPER ONE LEADS UP. A LOW HANDS AND KNEES PASSAGE ENTERS FROM THE SOUTH.`
	Rooms[104].LongDesc = `YOU ARE IN A LONG SLOPING CORRIDOR WITH RAGGED SHARP WALLS.`
	Rooms[105].LongDesc = `YOU ARE IN A CUL-DE-SAC ABOUT EIGHT FEET ACROSS.`
	Rooms[106].LongDesc = `YOU ARE IN AN ANTEROOM LEADING TO A LARGE PASSAGE TO THE EAST. SMALL PASSAGES GO WEST AND UP. THE REMNANTS OF RECENT DIGGING ARE EVIDENT. A SIGN IN MIDAIR HERE SAYS "CAVE UNDER CONSTRUCTION BEYOND THIS POINT. PROCEED AT OWN RISK. [WITT CONSTRUCTION COMPANY]"`
	Rooms[107].LongDesc = `YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL DIFFERENT.`
	Rooms[108].LongDesc = `YOU ARE AT WITT'S END. PASSAGES LEAD OFF IN *ALL* DIRECTIONS.`
	Rooms[109].LongDesc = `YOU ARE IN A NORTH/SOUTH CANYON ABOUT 25 FEET ACROSS. THE FLOOR IS COVERED BY WHITE MIST SEEPING IN FROM THE NORTH. THE WALLS EXTEND UPWARD FOR WELL OVER 100 FEET. SUSPENDED FROM SOME UNSEEN POINT FAR ABOVE YOU, AN ENORMOUS TWO-SIDED MIRROR IS HANGING PARALLEL TO AND MIDWAY BETWEEN THE CANYON WALLS. (THE MIRROR IS OBVIOUSLY PROVIDED FOR THE USE OF THE DWARVES, WHO AS YOU KNOW, ARE EXTREMELY VAIN.. A SMALL WINDOW CAN BE SEEN IN EITHER WALL, SOME FIFTY FEET UP.`
	Rooms[110].LongDesc = `YOU'RE AT A LOW WINDOW OVERLOOKING A HUGE PIT, WHICH EXTENDS UP OUT OF SIGHT. A FLOOR IS INDISTINCTLY VISIBLE OVER 50 FEET BELOW. TRACES OF WHITE MIST COVER THE FLOOR OF THE PIT, BECOMING THICKER TO THE LEFT. MARKS IN THE DUST AROUND THE WINDOW WOULD SEEM TO INDICATE THAT SOMEONE HAS BEEN HERE RECENTLY. DIRECTLY ACROSS THE PIT FROM YOU AND 25 FEET AWAY THERE IS A SIMILAR WINDOW LOOKING INTO A LIGHTED ROOM. A SHADOWY FIGURE CAN BE SEEN THERE PEERING BACK AT YOU.`
	Rooms[111].LongDesc = `A LARGE STALACTITE EXTENDS FROM THE ROOF AND ALMOST REACHES THE FLOOR BELOW. YOU COULD CLIMB DOWN IT, AND JUMP FROM IT TO THE FLOOR, BUT HAVING DONE SO YOU WOULD BE UNABLE TO REACH IT TO CLIMB BACK UP.`
	Rooms[112].LongDesc = `YOU ARE IN A LITTLE MAZE OF TWISTING PASSAGES, ALL DIFFERENT.`
	Rooms[113].LongDesc = `YOU ARE AT THE EDGE OF A LARGE UNDERGROUND RESERVOIR. AN OPAQUE CLOUD OF WHITE MIST FILLS THE ROOM AND RISES RAPIDLY UPWARD. THE LAKE IS FED BY A STREAM, WHICH TUMBLES OUT OF A HOLE IN THE WALL ABOUT 10 FEET OVERHEAD AND SPLASHES NOISILY INTO THE WATER SOMEWHERE WITHIN THE MIST. THE ONLY PASSAGE GOES BACK TOWARD THE SOUTH.`
	Rooms[114].LongDesc = `DEAD END`
	Rooms[115].LongDesc = `YOU ARE AT THE NORTHEAST END OF AN IMMENSE ROOM, EVEN LARGER THAN THE GIANT ROOM. IT APPEARS TO BE A REPOSITORY FOR THE "ADVENTURE" PROGRAM. MASSIVE TORCHES FAR OVERHEAD BATHE THE ROOM WITH SMOKY YELLOW LIGHT. SCATTERED ABOUT YOU CAN BE SEEN A PILE OF BOTTLES (ALL OF THEM EMPTY), A NURSERY OF YOUNG BEANSTALKS MURMURING QUIETLY, A BED OF OYSTERS, A BUNDLE OF BLACK RODS WITH RUSTY STARS ON THEIR ENDS, AND A COLLECTION OF BRASS LANTERNS. OFF TO ONE SIDE A GREAT MANY DWARVES ARE SLEEPING ON THE FLOOR, SNORING LOUDLY. A SIGN NEARBY READS: "DO NOT DISTURB THE DWARVES!. AN IMMENSE MIRROR IS HANGING AGAINST ONE WALL, AND STRETCHES TO THE OTHER END OF THE ROOM, WHERE VARIOUS OTHER SUNDRY OBJECTS CAN BE GLIMPSED DIMLY IN THE DISTANCE.`
	Rooms[116].LongDesc = `YOU ARE AT THE SOUTHWEST END OF THE REPOSITORY. TO ONE SIDE IS A PIT FULL OF FIERCE GREEN SNAKES. ON THE OTHER SIDE IS A ROW OF SMALL WICKER CAGES, EACH OF WHICH CONTAINS A LITTLE SULKING BIRD. IN ONE CORNER IS A BUNDLE OF BLACK RODS WITH RUSTY MARKS ON THEIR ENDS. A LARGE NUMBER OF VELVET PILLOWS ARE SCATTERED ABOUT ON THE FLOOR. A VAST MIRROR STRETCHES OFF TO THE NORTHEAST. AT YOUR FEET IS A LARGE STEEL GRATE, NEXT TO WHICH IS A SIGN WHICH READS, "TREASURE VAULT. KEYS IN MAIN OFFICE."`
	Rooms[117].LongDesc = `YOU ARE ON ONE SIDE OF A LARGE, DEEP CHASM. A HEAVY WHITE MIST RISING UP FROM BELOW OBSCURES ALL VIEW OF THE FAR SIDE. A SW PATH LEADS AWAY FROM THE CHASM INTO A WINDING CORRIDOR.`
	Rooms[118].LongDesc = `YOU ARE IN A LONG WINDING CORRIDOR SLOPING OUT OF SIGHT IN BOTH DIRECTIONS.`
	Rooms[119].LongDesc = `YOU ARE IN A SECRET CANYON WHICH EXITS TO THE NORTH AND EAST.`
	Rooms[120].LongDesc = `YOU ARE IN A SECRET CANYON WHICH EXITS TO THE NORTH AND EAST.`
	Rooms[121].LongDesc = `YOU ARE IN A SECRET CANYON WHICH EXITS TO THE NORTH AND EAST.`
	Rooms[122].LongDesc = `YOU ARE ON THE FAR SIDE OF THE CHASM. A NE PATH LEADS AWAY FROM THE CHASM ON THIS SIDE.`
	Rooms[123].LongDesc = `YOU'RE IN A LONG EAST/WEST CORRIDOR. A FAINT RUMBLING NOISE CAN BE HEARD IN THE DISTANCE.`
	Rooms[124].LongDesc = `THE PATH FORKS HERE. THE LEFT FORK LEADS NORTHEAST. A DULL RUMBLING SEEMS TO GET LOUDER IN THAT DIRECTION. THE RIGHT FORK LEADS SOUTHEAST DOWN A GENTLE SLOPE. THE MAIN CORRIDOR ENTERS FROM THE WEST.`
	Rooms[125].LongDesc = `THE WALLS ARE QUITE WARM HERE. FROM THE NORTH CAN BE HEARD A STEADY ROAR, SO LOUD THAT THE ENTIRE CAVE SEEMS TO BE TREMBLING. ANOTHER PASSAGE LEADS SOUTH, AND A LOW CRAWL GOES EAST.`
	Rooms[126].LongDesc = `YOU ARE ON THE EDGE OF A BREATH-TAKING VIEW. FAR BELOW YOU IS AN ACTIVE VOLCANO, FROM WHICH GREAT GOUTS OF MOLTEN LAVA COME SURGING OUT, CASCADING BACK DOWN INTO THE DEPTHS. THE GLOWING ROCK FILLS THE FARTHEST REACHES OF THE CAVERN WITH A BLOOD-RED GLARE, GIVING EVERY- THING AN EERIE, MACABRE APPEARANCE. THE AIR IS FILLED WITH FLICKERING SPARKS OF ASH AND A HEAVY SMELL OF BRIMSTONE. THE WALLS ARE HOT TO THE TOUCH, AND THE THUNDERING OF THE VOLCANO DROWNS OUT ALL OTHER SOUNDS. EMBEDDED IN THE JAGGED ROOF FAR OVERHEAD ARE MYRIAD TWISTED FORMATIONS COMPOSED OF PURE WHITE ALABASTER, WHICH SCATTER THE MURKY LIGHT INTO SINISTER APPARITIONS UPON THE WALLS. TO ONE SIDE IS A DEEP GORGE, FILLED WITH A BIZARRE CHAOS OF TORTURED ROCK WHICH SEEMS TO HAVE BEEN CRAFTED BY THE DEVIL HIMSELF. AN IMMENSE RIVER OF FIRE CRASHES OUT FROM THE DEPTHS OF THE VOLCANO, BURNS ITS WAY THROUGH THE GORGE, AND PLUMMETS INTO A BOTTOMLESS PIT FAR OFF TO YOUR LEFT. TO THE RIGHT, AN IMMENSE GEYSER OF BLISTERING STEAM ERUPTS CONTINUOUSLY FROM A BARREN ISLAND IN THE CENTER OF A SULFUROUS LAKE, WHICH BUBBLES OMINOUSLY. THE FAR RIGHT WALL IS AFLAME WITH AN INCANDESCENCE OF ITS OWN, WHICH LENDS AN ADDITIONAL INFERNAL SPLENDOR TO THE ALREADY HELLISH SCENE. A DARK, FOREBODING PASSAGE EXITS TO THE SOUTH.`
	Rooms[127].LongDesc = `YOU ARE IN A SMALL CHAMBER FILLED WITH LARGE BOULDERS. THE WALLS ARE VERY WARM, CAUSING THE AIR IN THE ROOM TO BE ALMOST STIFLING FROM THE HEAT. THE ONLY EXIT IS A CRAWL HEADING WEST, THROUGH WHICH IS COMING A LOW RUMBLING.`
	Rooms[128].LongDesc = `YOU ARE WALKING ALONG A GENTLY SLOPING NORTH/SOUTH PASSAGE LINED WITH ODDLY SHAPED LIMESTONE FORMATIONS.`
	Rooms[129].LongDesc = `YOU ARE STANDING AT THE ENTRANCE TO A LARGE, BARREN ROOM. A SIGN POSTED ABOVE THE ENTRANCE READS. "CAUTION. BEAR IN ROOM!"`
	Rooms[130].LongDesc = `YOU ARE INSIDE A BARREN ROOM. THE CENTER OF THE ROOM IS COMPLETELY EMPTY EXCEPT FOR SOME DUST. MARKS IN THE DUST LEAD AWAY TOWARD THE FAR END OF THE ROOM. THE ONLY EXIT IS THE WAY YOU CAME IN.`
	Rooms[131].LongDesc = `YOU ARE IN A MAZE OF TWISTING LITTLE PASSAGES, ALL DIFFERENT.`
	Rooms[132].LongDesc = `YOU ARE IN A LITTLE MAZE OF TWISTY PASSAGES, ALL DIFFERENT.`
	Rooms[133].LongDesc = `YOU ARE IN A TWISTING MAZE OF LITTLE PASSAGES, ALL DIFFERENT.`
	Rooms[134].LongDesc = `YOU ARE IN A TWISTING LITTLE MAZE OF PASSAGES, ALL DIFFERENT.`
	Rooms[135].LongDesc = `YOU ARE IN A TWISTY LITTLE MAZE OF PASSAGES, ALL DIFFERENT.`
	Rooms[136].LongDesc = `YOU ARE IN A TWISTY MAZE OF LITTLE PASSAGES, ALL DIFFERENT.`
	Rooms[137].LongDesc = `YOU ARE IN A LITTLE TWISTY MAZE OF PASSAGES, ALL DIFFERENT.`
	Rooms[138].LongDesc = `YOU ARE IN A MAZE OF LITTLE TWISTING PASSAGES, ALL DIFFERENT.`
	Rooms[139].LongDesc = `YOU ARE IN A MAZE OF LITTLE TWISTY PASSAGES, ALL DIFFERENT.`
	Rooms[140].LongDesc = `DEAD END`
}

func LoadShortDesc() {
	// short room descriptions, saves on char space
	Rooms[1].ShortDesc = `YOU'RE AT END OF ROAD AGAIN.`
	Rooms[2].ShortDesc = `YOU'RE AT HILL IN ROAD.`
	Rooms[3].ShortDesc = `YOU'RE INSIDE BUILDING.`
	Rooms[4].ShortDesc = `YOU'RE IN VALLEY.`
	Rooms[5].ShortDesc = `YOU'RE IN FOREST.`
	Rooms[6].ShortDesc = `YOU'RE IN FOREST.`
	Rooms[7].ShortDesc = `YOU'RE AT SLIT IN STREAMBED.`
	Rooms[8].ShortDesc = `YOU'RE OUTSIDE GRATE.`
	Rooms[9].ShortDesc = `YOU'RE BELOW THE GRATE.`
	Rooms[10].ShortDesc = `YOU'RE IN COBBLE CRAWL.`
	Rooms[11].ShortDesc = `YOU'RE IN DEBRIS ROOM.`
	Rooms[13].ShortDesc = `YOU'RE IN BIRD CHAMBER.`
	Rooms[14].ShortDesc = `YOU'RE AT TOP OF SMALL PIT.`
	Rooms[15].ShortDesc = `YOU'RE IN HALL OF MISTS.`
	Rooms[17].ShortDesc = `YOU'RE ON EAST BANK OF FISSURE.`
	Rooms[18].ShortDesc = `YOU'RE IN NUGGET OF GOLD ROOM.`
	Rooms[19].ShortDesc = `YOU'RE IN HALL OF MT KING`
	Rooms[23].ShortDesc = `YOU'RE AT WEST END OF TWOPIT ROOM.`
	Rooms[24].ShortDesc = `YOU'RE IN EAST PIT.`
	Rooms[25].ShortDesc = `YOU'RE IN WEST PIT.`
	Rooms[33].ShortDesc = `YOU'RE AT "Y2".`
	Rooms[35].ShortDesc = `YOU'RE AT WINDOW ON PIT.`
	Rooms[36].ShortDesc = `YOU'RE IN DIRTY PASSAGE.`
	Rooms[39].ShortDesc = `YOU'RE IN DUSTY ROCK ROOM.`
	Rooms[41].ShortDesc = `YOU'RE AT WEST END OF HALL OF MISTS.`
	Rooms[57].ShortDesc = `YOU'RE AT BRINK OF PIT.`
	Rooms[60].ShortDesc = `YOU'RE AT EAST END OF LONG HALL.`
	Rooms[61].ShortDesc = `YOU'RE AT WEST END OF LONG HALL.`
	Rooms[64].ShortDesc = `YOU'RE AT COMPLEX JUNCTION.`
	Rooms[66].ShortDesc = `YOU'RE IN SWISS CHEESE ROOM.`
	Rooms[67].ShortDesc = `YOU'RE AT EAST END OF TWOPIT ROOM.`
	Rooms[68].ShortDesc = `YOU'RE IN SLAB ROOM.`
	Rooms[71].ShortDesc = `YOU'RE AT JUNCTION OF THREE SECRET CANYONS.`
	Rooms[74].ShortDesc = `YOU'RE IN SECRET E/W CANYON ABOVE TIGHT CANYON.`
	Rooms[88].ShortDesc = `YOU'RE IN NARROW CORRIDOR.`
	Rooms[91].ShortDesc = `YOU'RE AT STEEP INCLINE ABOVE LARGE ROOM.`
	Rooms[92].ShortDesc = `YOU'RE IN GIANT ROOM.`
	Rooms[95].ShortDesc = `YOU'RE IN CAVERN WITH WATERFALL.`
	Rooms[96].ShortDesc = `YOU'RE IN SOFT ROOM.`
	Rooms[97].ShortDesc = `YOU'RE IN ORIENTAL ROOM.`
	Rooms[98].ShortDesc = `YOU'RE IN MISTY CAVERN.`
	Rooms[99].ShortDesc = `YOU'RE IN ALCOVE.`
	Rooms[100].ShortDesc = `YOU'RE IN PLOVER ROOM.`
	Rooms[101].ShortDesc = `YOU'RE IN DARK-ROOM.`
	Rooms[102].ShortDesc = `YOU'RE IN ARCHED HALL.`
	Rooms[103].ShortDesc = `YOU'RE IN SHELL ROOM.`
	Rooms[106].ShortDesc = `YOU'RE IN ANTEROOM.`
	Rooms[108].ShortDesc = `YOU'RE AT WITT'S END.`
	Rooms[109].ShortDesc = `YOU'RE IN MIRROR CANYON.`
	Rooms[110].ShortDesc = `YOU'RE AT WINDOW ON PIT.`
	Rooms[111].ShortDesc = `YOU'RE AT TOP OF STALACTITE.`
	Rooms[113].ShortDesc = `YOU'RE AT RESERVOIR.`
	Rooms[115].ShortDesc = `YOU'RE AT NE END.`
	Rooms[116].ShortDesc = `YOU'RE AT SW END.`
	Rooms[117].ShortDesc = `YOU'RE ON SW SIDE OF CHASM.`
	Rooms[118].ShortDesc = `YOU'RE IN SLOPING CORRIDOR.`
	Rooms[122].ShortDesc = `YOU'RE ON NE SIDE OF CHASM.`
	Rooms[123].ShortDesc = `YOU'RE IN CORRIDOR.`
	Rooms[124].ShortDesc = `YOU'RE AT FORK IN PATH.`
	Rooms[125].ShortDesc = `YOU'RE AT JUNCTION WITH WARM WALLS.`
	Rooms[126].ShortDesc = `YOU'RE AT BREATH-TAKING VIEW.`
	Rooms[127].ShortDesc = `YOU'RE IN CHAMBER OF BOULDERS.`
	Rooms[128].ShortDesc = `YOU'RE IN LIMESTONE PASSAGE.`
	Rooms[129].ShortDesc = `YOU'RE IN FRONT OF BARREN ROOM.`
	Rooms[130].ShortDesc = `YOU'RE IN BARREN ROOM.`
}

func LoadActions() {
	for i := 2; i <= 77; i++ {
		Actions[i] = &Action{}
	}
	// movement actions
	Actions[2].AcceptableStr = []string{`ROAD`, `HILL`}
	Actions[2].Id = 2
	Actions[3].AcceptableStr = []string{`ENTER`}
	Actions[3].Id = 3
	Actions[4].AcceptableStr = []string{`UPSTR`}
	Actions[4].Id = 4
	Actions[5].AcceptableStr = []string{`DOWNS`}
	Actions[5].Id = 5
	Actions[6].AcceptableStr = []string{`FORES`}
	Actions[6].Id = 6
	Actions[7].AcceptableStr = []string{`FORWA`, `CONTI`, `ONWAR`}
	Actions[7].Id = 7
	Actions[8].AcceptableStr = []string{`BACK`, `RETUR`, `RETRE`}
	Actions[8].Id = 8
	Actions[9].AcceptableStr = []string{`VALLE`}
	Actions[9].Id = 9
	Actions[10].AcceptableStr = []string{`STAIR`}
	Actions[10].Id = 10
	Actions[11].AcceptableStr = []string{`OUT`, `OUTSI`, `EXIT`, `LEAVE`}
	Actions[11].Id = 11
	Actions[12].AcceptableStr = []string{`BUILD`, `HOUSE`}
	Actions[12].Id = 12
	Actions[13].AcceptableStr = []string{`GULLY`}
	Actions[13].Id = 13
	Actions[14].AcceptableStr = []string{`STREA`}
	Actions[14].Id = 14
	Actions[15].AcceptableStr = []string{`ROCK`}
	Actions[15].Id = 15
	Actions[16].AcceptableStr = []string{`BED`}
	Actions[16].Id = 16
	Actions[17].AcceptableStr = []string{`CRAWL`}
	Actions[17].Id = 17
	Actions[18].AcceptableStr = []string{`COBBL`}
	Actions[18].Id = 18
	Actions[19].AcceptableStr = []string{`INWAR`, `INSID`, `IN`}
	Actions[19].Id = 19
	Actions[20].AcceptableStr = []string{`SURFA`}
	Actions[20].Id = 20
	Actions[21].AcceptableStr = []string{`NULL`, `NOWHE`}
	Actions[21].Id = 21
	Actions[22].AcceptableStr = []string{`DARK`}
	Actions[22].Id = 22
	Actions[23].AcceptableStr = []string{`PASSA`, `TUNNE`}
	Actions[23].Id = 23
	Actions[24].AcceptableStr = []string{`LOW`}
	Actions[24].Id = 24
	Actions[25].AcceptableStr = []string{`CANYO`}
	Actions[25].Id = 25
	Actions[26].AcceptableStr = []string{`AWKWA`}
	Actions[26].Id = 26
	Actions[27].AcceptableStr = []string{`GIANT`}
	Actions[27].Id = 27
	Actions[28].AcceptableStr = []string{`VIEW`}
	Actions[28].Id = 28
	Actions[29].AcceptableStr = []string{`UPWAR`, `UP`, `U`, `ABOVE`, `ASCEN`}
	Actions[29].Id = 29
	Actions[30].AcceptableStr = []string{`D`, `DOWNW`, `DOWN`, `DESCE`}
	Actions[30].Id = 30
	Actions[31].AcceptableStr = []string{`PIT`}
	Actions[31].Id = 31
	Actions[32].AcceptableStr = []string{`OUTDO`}
	Actions[32].Id = 32
	Actions[33].AcceptableStr = []string{`CRACK`}
	Actions[33].Id = 33
	Actions[34].AcceptableStr = []string{`STEPS`}
	Actions[34].Id = 34
	Actions[35].AcceptableStr = []string{`DOME`}
	Actions[35].Id = 35
	Actions[36].AcceptableStr = []string{`LEFT`}
	Actions[36].Id = 36
	Actions[37].AcceptableStr = []string{`RIGHT`}
	Actions[37].Id = 37
	Actions[38].AcceptableStr = []string{`HALL`}
	Actions[38].Id = 38
	Actions[39].AcceptableStr = []string{`JUMP`}
	Actions[39].Id = 39
	Actions[40].AcceptableStr = []string{`BARRE`}
	Actions[40].Id = 40
	Actions[41].AcceptableStr = []string{`OVER`}
	Actions[41].Id = 41
	Actions[42].AcceptableStr = []string{`ACROS`}
	Actions[42].Id = 42
	Actions[43].AcceptableStr = []string{`EAST`, `E`}
	Actions[43].Id = 43
	Actions[44].AcceptableStr = []string{`WEST`, `W`}
	Actions[44].Id = 44
	Actions[45].AcceptableStr = []string{`NORTH`, `N`}
	Actions[45].Id = 45
	Actions[46].AcceptableStr = []string{`SOUTH`, `S`}
	Actions[46].Id = 46
	Actions[47].AcceptableStr = []string{`NE`}
	Actions[47].Id = 47
	Actions[48].AcceptableStr = []string{`SE`}
	Actions[48].Id = 48
	Actions[49].AcceptableStr = []string{`SW`}
	Actions[49].Id = 49
	Actions[50].AcceptableStr = []string{`NW`}
	Actions[50].Id = 50
	Actions[51].AcceptableStr = []string{`DEBRI`}
	Actions[51].Id = 51
	Actions[52].AcceptableStr = []string{`HOLE`}
	Actions[52].Id = 52
	Actions[53].AcceptableStr = []string{`WALL`}
	Actions[53].Id = 53
	Actions[54].AcceptableStr = []string{`BROKE`}
	Actions[54].Id = 54
	Actions[55].AcceptableStr = []string{`Y2`}
	Actions[55].Id = 55
	Actions[56].AcceptableStr = []string{`CLIMB`}
	Actions[56].Id = 56
	Actions[57].AcceptableStr = []string{`LOOK`, `EXAMI`, `TOUCH`, `DESCR`}
	Actions[57].Id = 57
	Actions[58].AcceptableStr = []string{`FLOOR`}
	Actions[58].Id = 58
	Actions[59].AcceptableStr = []string{`ROOM`}
	Actions[59].Id = 59
	Actions[60].AcceptableStr = []string{`SLIT`}
	Actions[60].Id = 60
	Actions[61].AcceptableStr = []string{`SLAB`, `SLABR`}
	Actions[61].Id = 61
	Actions[62].AcceptableStr = []string{`XYZZY`}
	Actions[62].Id = 62
	Actions[63].AcceptableStr = []string{`DEPRE`}
	Actions[63].Id = 63
	Actions[64].AcceptableStr = []string{`ENTRA`}
	Actions[64].Id = 64
	Actions[65].AcceptableStr = []string{`PLUGH`}
	Actions[65].Id = 65
	Actions[66].AcceptableStr = []string{`SECRE`}
	Actions[66].Id = 66
	Actions[67].AcceptableStr = []string{`CAVE`}
	Actions[67].Id = 67
	Actions[69].AcceptableStr = []string{`CROSS`}
	Actions[69].Id = 69
	Actions[70].AcceptableStr = []string{`BEDQU`}
	Actions[70].Id = 70
	Actions[71].AcceptableStr = []string{`PLOVE`}
	Actions[71].Id = 71
	Actions[72].AcceptableStr = []string{`ORIEN`}
	Actions[72].Id = 72
	Actions[73].AcceptableStr = []string{`CAVER`}
	Actions[73].Id = 73
	Actions[74].AcceptableStr = []string{`SHELL`}
	Actions[74].Id = 74
	Actions[75].AcceptableStr = []string{`RESER`}
	Actions[75].Id = 75
	Actions[76].AcceptableStr = []string{`MAIN`, `OFFIC`}
	Actions[76].Id = 76
	Actions[77].AcceptableStr = []string{`FORK`}
	Actions[77].Id = 77

    // interactive actions, "take rod"
	Actions[2001] = &Action{}
	Actions[2001].AcceptableStr = []string{`CARRY`, `TAKE`, `KEEP`, `CATCH`, `STEAL`, `CAPTU`, `GET`, `TOTE`}
	Actions[2001].Id = 2001
	Actions[2002] = &Action{}
	Actions[2002].AcceptableStr = []string{`DROP`, `RELEA`, `FREE`, `DISCA`, `DUMP`}
	Actions[2002].Id = 2002
	Actions[2003] = &Action{}
	Actions[2003].AcceptableStr = []string{`SAY`, `CHANT`, `SING`, `UTTER`, `MUMBL`}
	Actions[2003].Id = 2003
	Actions[2004] = &Action{}
	Actions[2004].AcceptableStr = []string{`UNLOC`, `OPEN`}
	Actions[2004].Id = 2004
	Actions[2005] = &Action{}
	Actions[2005].AcceptableStr = []string{`NOTHI`}
	Actions[2005].Id = 2005
	Actions[2006] = &Action{}
	Actions[2006].AcceptableStr = []string{`LOCK`, `CLOSE`}
	Actions[2006].Id = 2006
	Actions[2007] = &Action{}
	Actions[2007].AcceptableStr = []string{`LIGHT`, `ON`}
	Actions[2007].Id = 2007
	Actions[2008] = &Action{}
	Actions[2008].AcceptableStr = []string{`EXTIN`, `OFF`}
	Actions[2008].Id = 2008
	Actions[2009] = &Action{}
	Actions[2009].AcceptableStr = []string{`WAVE`, `SHAKE`, `SWING`}
	Actions[2009].Id = 2009
	Actions[2010] = &Action{}
	Actions[2010].AcceptableStr = []string{`CALM`, `PLACA`, `TAME`}
	Actions[2010].Id = 2010
	Actions[2011] = &Action{}
	Actions[2011].AcceptableStr = []string{`WALK`, `RUN`, `TRAVE`, `GO`, `PROCE`, `CONTI`, `EXPLO`, `GOTO`, `FOLLO`, `TURN`}
	Actions[2011].Id = 2011
	Actions[2012] = &Action{}
	Actions[2012].AcceptableStr = []string{`ATTAC`, `KILL`, `FIGHT`, `HIT`, `STRIK`}
	Actions[2012].Id = 2012
	Actions[2013] = &Action{}
	Actions[2013].AcceptableStr = []string{`POUR`}
	Actions[2013].Id = 2013
	Actions[2014] = &Action{}
	Actions[2014].AcceptableStr = []string{`EAT`, `DEVOU`}
	Actions[2014].Id = 2014
	Actions[2015] = &Action{}
	Actions[2015].AcceptableStr = []string{`DRINK`}
	Actions[2015].Id = 2015
	Actions[2016] = &Action{}
	Actions[2016].AcceptableStr = []string{`RUB`}
	Actions[2016].Id = 2016
	Actions[2017] = &Action{}
	Actions[2017].AcceptableStr = []string{`THROW`, `TOSS`}
	Actions[2017].Id = 2017
	Actions[2018] = &Action{}
	Actions[2018].AcceptableStr = []string{`QUIT`}
	Actions[2018].Id = 2018
	Actions[2019] = &Action{}
	Actions[2019].AcceptableStr = []string{`FIND`, `WHERE`}
	Actions[2019].Id = 2019
	Actions[2020] = &Action{}
	Actions[2020].AcceptableStr = []string{`INVEN`}
	Actions[2020].Id = 2020
	Actions[2021] = &Action{}
	Actions[2021].AcceptableStr = []string{`FEED`}
	Actions[2021].Id = 2021
	Actions[2022] = &Action{}
	Actions[2022].AcceptableStr = []string{`FILL`}
	Actions[2022].Id = 2022
	Actions[2023] = &Action{}
	Actions[2023].AcceptableStr = []string{`BLAST`, `DETON`, `IGNIT`, `BLOWU`}
	Actions[2023].Id = 2023
	Actions[2024] = &Action{}
	Actions[2024].AcceptableStr = []string{`SCORE`}
	Actions[2024].Id = 2024
	Actions[2025] = &Action{}
	Actions[2025].AcceptableStr = []string{`FEE`, `FIE`, `FOE`, `FOO`, `FUM`}
	Actions[2025].Id = 2025
	Actions[2026] = &Action{}
	Actions[2026].AcceptableStr = []string{`BRIEF`}
	Actions[2026].Id = 2026
	Actions[2027] = &Action{}
	Actions[2027].AcceptableStr = []string{`READ`, `PERUS`}
	Actions[2027].Id = 2027
	Actions[2028] = &Action{}
	Actions[2028].AcceptableStr = []string{`BREAK`, `SHATT`, `SMASH`}
	Actions[2028].Id = 2028
	Actions[2029] = &Action{}
	Actions[2029].AcceptableStr = []string{`WAKE`, `DISTU`}
	Actions[2029].Id = 2029
	Actions[2030] = &Action{}
	Actions[2030].AcceptableStr = []string{`SUSPE`, `PAUSE`, `SAVE`}
	Actions[2030].Id = 2030
	Actions[2031] = &Action{}
	Actions[2031].AcceptableStr = []string{`HOURS`}
	Actions[2031].Id = 2031

	// special case verbs
	Actions[3001] = &Action{}
	Actions[3001].AcceptableStr = []string{`FEE`}
	Actions[3001].Id = 3001
	Actions[3002] = &Action{}
	Actions[3002].AcceptableStr = []string{`FIE`}
	Actions[3002].Id = 3002
	Actions[3003] = &Action{}
	Actions[3003].AcceptableStr = []string{`FOE`}
	Actions[3003].Id = 3003
	Actions[3004] = &Action{}
	Actions[3004].AcceptableStr = []string{`FOO`}
	Actions[3004].Id = 3004
	Actions[3005] = &Action{}
	Actions[3005].AcceptableStr = []string{`FUM`}
	Actions[3005].Id = 3005
	Actions[3050] = &Action{}
	Actions[3050].AcceptableStr = []string{`SESAM`, `OPENS`, `ABRA`, `ABRAC`, `SHAZA`, `HOCUS`, `POCUS`}
	Actions[3050].Id = 3050
	Actions[3051] = &Action{}
	Actions[3051].AcceptableStr = []string{`HELP`, `?`}
	Actions[3051].Id = 3051
	Actions[3064] = &Action{}
	Actions[3064].AcceptableStr = []string{`TREE`, `TREES`}
	Actions[3064].Id = 3064
	Actions[3066] = &Action{}
	Actions[3066].AcceptableStr = []string{`DIG`, `EXCAV`}
	Actions[3066].Id = 3066
	Actions[3068] = &Action{}
	Actions[3068].AcceptableStr = []string{`LOST`}
	Actions[3068].Id = 3068
	Actions[3069] = &Action{}
	Actions[3069].AcceptableStr = []string{`MIST`}
	Actions[3069].Id = 3069
	Actions[3079] = &Action{}
	Actions[3079].AcceptableStr = []string{`FUCK`}
	Actions[3079].Id = 3079
	Actions[3139] = &Action{}
	Actions[3139].AcceptableStr = []string{`STOP`}
	Actions[3139].Id = 3139
	Actions[3142] = &Action{}
	Actions[3142].AcceptableStr = []string{`INFO`, `INFOR`}
	Actions[3142].Id = 3142
	Actions[3147] = &Action{}
	Actions[3147].AcceptableStr = []string{`SWIM`}
	Actions[3147].Id = 3147
}

func LoadTravel() {
	// Rooms[origin].Connection[action] = destination
	Rooms[1].Connection[2] = 2
	Rooms[1].Connection[44] = 2
	Rooms[1].Connection[29] = 2
	Rooms[1].Connection[3] = 3
	Rooms[1].Connection[12] = 3
	Rooms[1].Connection[19] = 3
	Rooms[1].Connection[43] = 3
	Rooms[1].Connection[5] = 4
	Rooms[1].Connection[13] = 4
	Rooms[1].Connection[14] = 4
	Rooms[1].Connection[46] = 4
	Rooms[1].Connection[30] = 4
	Rooms[1].Connection[6] = 5
	Rooms[1].Connection[45] = 5
	Rooms[1].Connection[43] = 5
	Rooms[1].Connection[63] = 8
	Rooms[2].Connection[2] = 1
	Rooms[2].Connection[12] = 1
	Rooms[2].Connection[7] = 1
	Rooms[2].Connection[43] = 1
	Rooms[2].Connection[45] = 1
	Rooms[2].Connection[30] = 1
	Rooms[2].Connection[6] = 5
	Rooms[2].Connection[45] = 5
	Rooms[2].Connection[46] = 5
	Rooms[3].Connection[3] = 1
	Rooms[3].Connection[11] = 1
	Rooms[3].Connection[32] = 1
	Rooms[3].Connection[44] = 1
	Rooms[3].Connection[62] = 11
	Rooms[3].Connection[65] = 33
	Rooms[3].Connection[5] = 79
	Rooms[3].Connection[14] = 79
	Rooms[4].Connection[4] = 1
	Rooms[4].Connection[12] = 1
	Rooms[4].Connection[45] = 1
	Rooms[4].Connection[6] = 5
	Rooms[4].Connection[43] = 5
	Rooms[4].Connection[44] = 5
	Rooms[4].Connection[29] = 5
	Rooms[4].Connection[5] = 7
	Rooms[4].Connection[46] = 7
	Rooms[4].Connection[30] = 7
	Rooms[4].Connection[63] = 8
	Rooms[5].Connection[9] = 4
	Rooms[5].Connection[43] = 4
	Rooms[5].Connection[30] = 4
	Rooms[5].Connection[6] = 50005
	Rooms[5].Connection[7] = 50005
	Rooms[5].Connection[45] = 50005
	Rooms[5].Connection[6] = 6
	Rooms[5].Connection[44] = 5
	Rooms[5].Connection[46] = 5
	Rooms[6].Connection[2] = 1
	Rooms[6].Connection[45] = 1
	Rooms[6].Connection[9] = 4
	Rooms[6].Connection[43] = 4
	Rooms[6].Connection[44] = 4
	Rooms[6].Connection[30] = 4
	Rooms[6].Connection[6] = 5
	Rooms[6].Connection[46] = 5
	Rooms[7].Connection[12] = 1
	Rooms[7].Connection[4] = 4
	Rooms[7].Connection[45] = 4
	Rooms[7].Connection[6] = 5
	Rooms[7].Connection[43] = 5
	Rooms[7].Connection[44] = 5
	Rooms[7].Connection[5] = 8
	Rooms[7].Connection[15] = 8
	Rooms[7].Connection[16] = 8
	Rooms[7].Connection[46] = 8
	Rooms[7].Connection[60] = 595
	Rooms[7].Connection[14] = 595
	Rooms[7].Connection[30] = 595
	Rooms[8].Connection[6] = 5
	Rooms[8].Connection[43] = 5
	Rooms[8].Connection[44] = 5
	Rooms[8].Connection[46] = 5
	Rooms[8].Connection[12] = 1
	Rooms[8].Connection[4] = 7
	Rooms[8].Connection[13] = 7
	Rooms[8].Connection[45] = 7
	Rooms[8].Connection[3] = 303009
	Rooms[8].Connection[19] = 303009
	Rooms[8].Connection[30] = 303009
	Rooms[8].Connection[3] = 593
	Rooms[9].Connection[11] = 303008
	Rooms[9].Connection[29] = 303008
	Rooms[9].Connection[11] = 593
	Rooms[9].Connection[17] = 10
	Rooms[9].Connection[18] = 10
	Rooms[9].Connection[19] = 10
	Rooms[9].Connection[44] = 10
	Rooms[9].Connection[31] = 14
	Rooms[9].Connection[51] = 11
	Rooms[10].Connection[11] = 9
	Rooms[10].Connection[20] = 9
	Rooms[10].Connection[21] = 9
	Rooms[10].Connection[43] = 9
	Rooms[10].Connection[19] = 11
	Rooms[10].Connection[22] = 11
	Rooms[10].Connection[44] = 11
	Rooms[10].Connection[51] = 11
	Rooms[10].Connection[31] = 14
	Rooms[11].Connection[63] = 303008
	Rooms[11].Connection[64] = 9
	Rooms[11].Connection[17] = 10
	Rooms[11].Connection[18] = 10
	Rooms[11].Connection[23] = 10
	Rooms[11].Connection[24] = 10
	Rooms[11].Connection[43] = 10
	Rooms[11].Connection[25] = 12
	Rooms[11].Connection[19] = 12
	Rooms[11].Connection[29] = 12
	Rooms[11].Connection[44] = 12
	Rooms[11].Connection[62] = 3
	Rooms[11].Connection[31] = 14
	Rooms[12].Connection[63] = 303008
	Rooms[12].Connection[64] = 9
	Rooms[12].Connection[30] = 11
	Rooms[12].Connection[43] = 11
	Rooms[12].Connection[51] = 11
	Rooms[12].Connection[19] = 13
	Rooms[12].Connection[29] = 13
	Rooms[12].Connection[44] = 13
	Rooms[12].Connection[31] = 14
	Rooms[13].Connection[63] = 303008
	Rooms[13].Connection[64] = 9
	Rooms[13].Connection[51] = 11
	Rooms[13].Connection[25] = 12
	Rooms[13].Connection[43] = 12
	Rooms[13].Connection[23] = 14
	Rooms[13].Connection[31] = 14
	Rooms[13].Connection[44] = 14
	Rooms[14].Connection[63] = 303008
	Rooms[14].Connection[64] = 9
	Rooms[14].Connection[51] = 11
	Rooms[14].Connection[23] = 13
	Rooms[14].Connection[43] = 13
	Rooms[14].Connection[30] = 150020
	Rooms[14].Connection[31] = 150020
	Rooms[14].Connection[34] = 150020
	Rooms[14].Connection[30] = 15
	Rooms[14].Connection[33] = 16
	Rooms[14].Connection[44] = 16
	Rooms[15].Connection[36] = 18
	Rooms[15].Connection[46] = 18
	Rooms[15].Connection[7] = 17
	Rooms[15].Connection[38] = 17
	Rooms[15].Connection[44] = 17
	Rooms[15].Connection[10] = 19
	Rooms[15].Connection[30] = 19
	Rooms[15].Connection[45] = 19
	Rooms[15].Connection[29] = 150022
	Rooms[15].Connection[31] = 150022
	Rooms[15].Connection[34] = 150022
	Rooms[15].Connection[35] = 150022
	Rooms[15].Connection[23] = 150022
	Rooms[15].Connection[43] = 150022
	Rooms[15].Connection[29] = 14
	Rooms[15].Connection[55] = 34
	Rooms[16].Connection[1] = 14
	Rooms[17].Connection[38] = 15
	Rooms[17].Connection[43] = 15
	Rooms[17].Connection[39] = 312596
	Rooms[17].Connection[7] = 412021
	Rooms[17].Connection[41] = 412597
	Rooms[17].Connection[42] = 412597
	Rooms[17].Connection[44] = 412597
	Rooms[17].Connection[69] = 412597
	Rooms[17].Connection[41] = 27
	Rooms[18].Connection[38] = 15
	Rooms[18].Connection[11] = 15
	Rooms[18].Connection[45] = 15
	Rooms[19].Connection[10] = 15
	Rooms[19].Connection[29] = 15
	Rooms[19].Connection[43] = 15
	Rooms[19].Connection[45] = 311028
	Rooms[19].Connection[36] = 311028
	Rooms[19].Connection[46] = 311029
	Rooms[19].Connection[37] = 311029
	Rooms[19].Connection[44] = 311030
	Rooms[19].Connection[7] = 311030
	Rooms[19].Connection[45] = 32
	Rooms[19].Connection[49] = 35074
	Rooms[19].Connection[49] = 211032
	Rooms[19].Connection[66] = 74
	Rooms[20].Connection[1] = 0
	Rooms[21].Connection[1] = 0
	Rooms[22].Connection[1] = 15
	Rooms[23].Connection[43] = 67
	Rooms[23].Connection[42] = 67
	Rooms[23].Connection[44] = 68
	Rooms[23].Connection[61] = 68
	Rooms[23].Connection[30] = 25
	Rooms[23].Connection[31] = 25
	Rooms[23].Connection[52] = 648
	Rooms[24].Connection[29] = 67
	Rooms[24].Connection[11] = 67
	Rooms[25].Connection[29] = 23
	Rooms[25].Connection[11] = 23
	Rooms[25].Connection[56] = 724031
	Rooms[25].Connection[56] = 26
	Rooms[26].Connection[1] = 88
	Rooms[27].Connection[39] = 312596
	Rooms[27].Connection[7] = 412021
	Rooms[27].Connection[41] = 412597
	Rooms[27].Connection[69] = 412597
	Rooms[27].Connection[43] = 412597
	Rooms[27].Connection[42] = 412597
	Rooms[27].Connection[41] = 17
	Rooms[27].Connection[45] = 40
	Rooms[27].Connection[44] = 41
	Rooms[28].Connection[38] = 19
	Rooms[28].Connection[46] = 19
	Rooms[28].Connection[11] = 19
	Rooms[28].Connection[45] = 33
	Rooms[28].Connection[55] = 33
	Rooms[28].Connection[30] = 36
	Rooms[28].Connection[52] = 36
	Rooms[29].Connection[38] = 19
	Rooms[29].Connection[45] = 19
	Rooms[29].Connection[11] = 19
	Rooms[29].Connection[38] = 19
	Rooms[29].Connection[43] = 19
	Rooms[29].Connection[11] = 19
	Rooms[30].Connection[44] = 62
	Rooms[30].Connection[29] = 62
	Rooms[31].Connection[1] = 524089
	Rooms[31].Connection[1] = 90
	Rooms[32].Connection[1] = 19
	Rooms[33].Connection[65] = 3
	Rooms[33].Connection[46] = 28
	Rooms[33].Connection[43] = 34
	Rooms[33].Connection[54] = 34
	Rooms[33].Connection[53] = 34
	Rooms[33].Connection[44] = 35
	Rooms[33].Connection[71] = 159302
	Rooms[33].Connection[71] = 100
	Rooms[34].Connection[30] = 33
	Rooms[34].Connection[55] = 33
	Rooms[34].Connection[29] = 15
	Rooms[35].Connection[43] = 33
	Rooms[35].Connection[55] = 33
	Rooms[35].Connection[39] = 20
	Rooms[36].Connection[43] = 37
	Rooms[36].Connection[17] = 37
	Rooms[36].Connection[29] = 28
	Rooms[36].Connection[52] = 28
	Rooms[36].Connection[44] = 39
	Rooms[36].Connection[70] = 65
	Rooms[37].Connection[44] = 36
	Rooms[37].Connection[17] = 36
	Rooms[37].Connection[30] = 38
	Rooms[37].Connection[56] = 38
	Rooms[37].Connection[31] = 38
	Rooms[38].Connection[56] = 37
	Rooms[38].Connection[11] = 37
	Rooms[38].Connection[29] = 37
	Rooms[38].Connection[60] = 595
	Rooms[38].Connection[5] = 595
	Rooms[38].Connection[4] = 595
	Rooms[38].Connection[30] = 595
	Rooms[38].Connection[14] = 595
	Rooms[39].Connection[43] = 36
	Rooms[39].Connection[23] = 36
	Rooms[39].Connection[30] = 64
	Rooms[39].Connection[58] = 64
	Rooms[39].Connection[52] = 64
	Rooms[39].Connection[70] = 65
	Rooms[40].Connection[1] = 41
	Rooms[41].Connection[46] = 42
	Rooms[41].Connection[56] = 42
	Rooms[41].Connection[23] = 42
	Rooms[41].Connection[29] = 42
	Rooms[41].Connection[43] = 27
	Rooms[41].Connection[45] = 59
	Rooms[41].Connection[44] = 60
	Rooms[41].Connection[17] = 60
	Rooms[42].Connection[29] = 41
	Rooms[42].Connection[45] = 42
	Rooms[42].Connection[43] = 43
	Rooms[42].Connection[46] = 45
	Rooms[42].Connection[44] = 80
	Rooms[43].Connection[44] = 42
	Rooms[43].Connection[46] = 44
	Rooms[43].Connection[43] = 45
	Rooms[44].Connection[43] = 43
	Rooms[44].Connection[30] = 48
	Rooms[44].Connection[46] = 50
	Rooms[44].Connection[45] = 82
	Rooms[45].Connection[44] = 42
	Rooms[45].Connection[45] = 43
	Rooms[45].Connection[43] = 46
	Rooms[45].Connection[46] = 47
	Rooms[45].Connection[29] = 87
	Rooms[45].Connection[30] = 87
	Rooms[46].Connection[44] = 45
	Rooms[46].Connection[11] = 45
	Rooms[47].Connection[43] = 45
	Rooms[47].Connection[11] = 45
	Rooms[48].Connection[29] = 44
	Rooms[48].Connection[11] = 44
	Rooms[49].Connection[43] = 50
	Rooms[49].Connection[44] = 51
	Rooms[50].Connection[43] = 44
	Rooms[50].Connection[44] = 49
	Rooms[50].Connection[30] = 51
	Rooms[50].Connection[46] = 52
	Rooms[51].Connection[44] = 49
	Rooms[51].Connection[29] = 50
	Rooms[51].Connection[43] = 52
	Rooms[51].Connection[46] = 53
	Rooms[52].Connection[44] = 50
	Rooms[52].Connection[43] = 51
	Rooms[52].Connection[46] = 52
	Rooms[52].Connection[29] = 53
	Rooms[52].Connection[45] = 55
	Rooms[52].Connection[30] = 86
	Rooms[53].Connection[44] = 51
	Rooms[53].Connection[45] = 52
	Rooms[53].Connection[46] = 54
	Rooms[54].Connection[44] = 53
	Rooms[54].Connection[11] = 53
	Rooms[55].Connection[44] = 52
	Rooms[55].Connection[45] = 55
	Rooms[55].Connection[30] = 56
	Rooms[55].Connection[43] = 57
	Rooms[56].Connection[29] = 55
	Rooms[56].Connection[11] = 55
	Rooms[57].Connection[30] = 13
	Rooms[57].Connection[56] = 13
	Rooms[57].Connection[44] = 55
	Rooms[57].Connection[46] = 58
	Rooms[57].Connection[45] = 83
	Rooms[57].Connection[43] = 84
	Rooms[58].Connection[43] = 57
	Rooms[58].Connection[11] = 57
	Rooms[59].Connection[1] = 27
	Rooms[60].Connection[43] = 41
	Rooms[60].Connection[17] = 41
	Rooms[60].Connection[29] = 41
	Rooms[60].Connection[44] = 61
	Rooms[60].Connection[45] = 62
	Rooms[60].Connection[52] = 62
	Rooms[60].Connection[30] = 62
	Rooms[61].Connection[43] = 60
	Rooms[61].Connection[45] = 62
	Rooms[61].Connection[46] = 100107
	Rooms[62].Connection[44] = 60
	Rooms[62].Connection[45] = 63
	Rooms[62].Connection[43] = 30
	Rooms[62].Connection[46] = 61
	Rooms[63].Connection[46] = 62
	Rooms[63].Connection[11] = 62
	Rooms[64].Connection[29] = 39
	Rooms[64].Connection[59] = 39
	Rooms[64].Connection[56] = 39
	Rooms[64].Connection[44] = 65
	Rooms[64].Connection[70] = 65
	Rooms[64].Connection[45] = 103
	Rooms[64].Connection[74] = 103
	Rooms[64].Connection[43] = 106
	Rooms[65].Connection[43] = 64
	Rooms[65].Connection[44] = 66
	Rooms[65].Connection[46] = 80556
	Rooms[65].Connection[61] = 68
	Rooms[65].Connection[29] = 80556
	Rooms[65].Connection[29] = 50070
	Rooms[65].Connection[29] = 39
	Rooms[65].Connection[45] = 60556
	Rooms[65].Connection[45] = 75072
	Rooms[65].Connection[45] = 71
	Rooms[65].Connection[30] = 80556
	Rooms[65].Connection[30] = 106
	Rooms[66].Connection[47] = 65
	Rooms[66].Connection[44] = 67
	Rooms[66].Connection[46] = 80556
	Rooms[66].Connection[25] = 77
	Rooms[66].Connection[43] = 96
	Rooms[66].Connection[50] = 50556
	Rooms[66].Connection[72] = 97
	Rooms[67].Connection[43] = 66
	Rooms[67].Connection[44] = 23
	Rooms[67].Connection[42] = 23
	Rooms[67].Connection[30] = 24
	Rooms[67].Connection[31] = 24
	Rooms[68].Connection[46] = 23
	Rooms[68].Connection[29] = 69
	Rooms[68].Connection[56] = 69
	Rooms[68].Connection[45] = 65
	Rooms[69].Connection[30] = 68
	Rooms[69].Connection[61] = 68
	Rooms[69].Connection[46] = 331120
	Rooms[69].Connection[46] = 119
	Rooms[69].Connection[45] = 109
	Rooms[69].Connection[75] = 113
	Rooms[70].Connection[45] = 71
	Rooms[70].Connection[30] = 65
	Rooms[70].Connection[23] = 65
	Rooms[70].Connection[46] = 111
	Rooms[71].Connection[48] = 65
	Rooms[71].Connection[46] = 70
	Rooms[71].Connection[45] = 110
	Rooms[72].Connection[70] = 65
	Rooms[72].Connection[49] = 118
	Rooms[72].Connection[45] = 73
	Rooms[72].Connection[48] = 97
	Rooms[72].Connection[72] = 97
	Rooms[73].Connection[46] = 72
	Rooms[73].Connection[11] = 72
	Rooms[73].Connection[17] = 72
	Rooms[74].Connection[43] = 19
	Rooms[74].Connection[44] = 331120
	Rooms[74].Connection[44] = 121
	Rooms[74].Connection[30] = 75
	Rooms[75].Connection[46] = 76
	Rooms[75].Connection[45] = 77
	Rooms[76].Connection[45] = 75
	Rooms[77].Connection[43] = 75
	Rooms[77].Connection[44] = 78
	Rooms[77].Connection[45] = 66
	Rooms[77].Connection[17] = 66
	Rooms[78].Connection[46] = 77
	Rooms[79].Connection[1] = 3
	Rooms[80].Connection[45] = 42
	Rooms[80].Connection[44] = 80
	Rooms[80].Connection[46] = 80
	Rooms[80].Connection[43] = 81
	Rooms[81].Connection[44] = 80
	Rooms[81].Connection[11] = 80
	Rooms[82].Connection[46] = 44
	Rooms[82].Connection[11] = 44
	Rooms[83].Connection[46] = 57
	Rooms[83].Connection[43] = 84
	Rooms[83].Connection[44] = 85
	Rooms[84].Connection[45] = 57
	Rooms[84].Connection[44] = 83
	Rooms[84].Connection[50] = 114
	Rooms[85].Connection[43] = 83
	Rooms[85].Connection[11] = 83
	Rooms[86].Connection[29] = 52
	Rooms[86].Connection[11] = 52
	Rooms[87].Connection[29] = 45
	Rooms[87].Connection[30] = 45
	Rooms[88].Connection[30] = 25
	Rooms[88].Connection[43] = 25
	Rooms[88].Connection[56] = 25
	Rooms[88].Connection[39] = 20
	Rooms[88].Connection[44] = 92
	Rooms[88].Connection[27] = 92
	Rooms[89].Connection[1] = 25
	Rooms[90].Connection[1] = 23
	Rooms[91].Connection[45] = 95
	Rooms[91].Connection[23] = 95
	Rooms[91].Connection[73] = 95
	Rooms[91].Connection[30] = 72
	Rooms[91].Connection[56] = 72
	Rooms[92].Connection[46] = 88
	Rooms[92].Connection[43] = 93
	Rooms[92].Connection[45] = 94
	Rooms[93].Connection[46] = 92
	Rooms[93].Connection[11] = 92
	Rooms[93].Connection[27] = 92
	Rooms[94].Connection[46] = 92
	Rooms[94].Connection[23] = 92
	Rooms[94].Connection[27] = 92
	Rooms[94].Connection[45] = 309095
	Rooms[94].Connection[73] = 309095
	Rooms[94].Connection[3] = 309095
	Rooms[94].Connection[45] = 611
	Rooms[95].Connection[46] = 94
	Rooms[95].Connection[11] = 94
	Rooms[95].Connection[27] = 92
	Rooms[95].Connection[44] = 91
	Rooms[96].Connection[44] = 66
	Rooms[96].Connection[11] = 66
	Rooms[97].Connection[48] = 66
	Rooms[97].Connection[44] = 72
	Rooms[97].Connection[17] = 72
	Rooms[97].Connection[29] = 98
	Rooms[97].Connection[73] = 98
	Rooms[97].Connection[45] = 98
	Rooms[98].Connection[46] = 97
	Rooms[98].Connection[72] = 97
	Rooms[98].Connection[44] = 99
	Rooms[99].Connection[50] = 98
	Rooms[99].Connection[73] = 98
	Rooms[99].Connection[43] = 301
	Rooms[99].Connection[23] = 301
	Rooms[99].Connection[43] = 100
	Rooms[100].Connection[44] = 301
	Rooms[100].Connection[11] = 301
	Rooms[100].Connection[23] = 301
	Rooms[100].Connection[44] = 99
	Rooms[100].Connection[71] = 159302
	Rooms[100].Connection[71] = 33
	Rooms[100].Connection[47] = 101
	Rooms[100].Connection[22] = 101
	Rooms[101].Connection[46] = 100
	Rooms[101].Connection[11] = 100
	Rooms[101].Connection[71] = 100
	Rooms[102].Connection[30] = 103
	Rooms[102].Connection[11] = 103
	Rooms[102].Connection[74] = 103
	Rooms[103].Connection[29] = 102
	Rooms[103].Connection[38] = 102
	Rooms[103].Connection[30] = 104
	Rooms[103].Connection[46] = 114618
	Rooms[103].Connection[46] = 115619
	Rooms[103].Connection[46] = 64
	Rooms[104].Connection[29] = 103
	Rooms[104].Connection[74] = 103
	Rooms[104].Connection[30] = 105
	Rooms[105].Connection[29] = 104
	Rooms[105].Connection[11] = 104
	Rooms[105].Connection[74] = 103
	Rooms[106].Connection[29] = 64
	Rooms[106].Connection[44] = 65
	Rooms[106].Connection[43] = 108
	Rooms[107].Connection[46] = 131
	Rooms[107].Connection[49] = 132
	Rooms[107].Connection[47] = 133
	Rooms[107].Connection[48] = 134
	Rooms[107].Connection[29] = 135
	Rooms[107].Connection[50] = 136
	Rooms[107].Connection[43] = 137
	Rooms[107].Connection[44] = 138
	Rooms[107].Connection[45] = 139
	Rooms[107].Connection[30] = 61
	Rooms[108].Connection[43] = 95556
	Rooms[108].Connection[30] = 95556
	Rooms[108].Connection[29] = 95556
	Rooms[108].Connection[50] = 95556
	Rooms[108].Connection[49] = 95556
	Rooms[108].Connection[48] = 95556
	Rooms[108].Connection[47] = 95556
	Rooms[108].Connection[46] = 95556
	Rooms[108].Connection[45] = 95556
	Rooms[108].Connection[43] = 106
	Rooms[108].Connection[44] = 626
	Rooms[109].Connection[46] = 69
	Rooms[109].Connection[45] = 113
	Rooms[109].Connection[75] = 113
	Rooms[110].Connection[44] = 71
	Rooms[110].Connection[39] = 20
	Rooms[111].Connection[45] = 70
	Rooms[111].Connection[30] = 40050
	Rooms[111].Connection[56] = 40050
	Rooms[111].Connection[39] = 40050
	Rooms[111].Connection[30] = 50053
	Rooms[111].Connection[30] = 45
	Rooms[112].Connection[49] = 131
	Rooms[112].Connection[45] = 132
	Rooms[112].Connection[43] = 133
	Rooms[112].Connection[50] = 134
	Rooms[112].Connection[48] = 135
	Rooms[112].Connection[47] = 136
	Rooms[112].Connection[44] = 137
	Rooms[112].Connection[30] = 138
	Rooms[112].Connection[29] = 139
	Rooms[112].Connection[46] = 140
	Rooms[113].Connection[46] = 109
	Rooms[113].Connection[109] = 109
	Rooms[113].Connection[11] = 109
	Rooms[114].Connection[48] = 84
	Rooms[115].Connection[49] = 116
	Rooms[116].Connection[47] = 115
	Rooms[116].Connection[30] = 593
	Rooms[117].Connection[49] = 118
	Rooms[117].Connection[41] = 233660
	Rooms[117].Connection[47] = 233660
	Rooms[117].Connection[69] = 233660
	Rooms[117].Connection[42] = 233660
	Rooms[117].Connection[41] = 332661
	Rooms[117].Connection[41] = 303
	Rooms[117].Connection[39] = 332021
	Rooms[117].Connection[39] = 596
	Rooms[118].Connection[30] = 72
	Rooms[118].Connection[29] = 117
	Rooms[119].Connection[45] = 69
	Rooms[119].Connection[11] = 69
	Rooms[119].Connection[43] = 653
	Rooms[119].Connection[7] = 653
	Rooms[120].Connection[45] = 69
	Rooms[120].Connection[43] = 74
	Rooms[121].Connection[43] = 74
	Rooms[121].Connection[11] = 74
	Rooms[121].Connection[45] = 653
	Rooms[121].Connection[7] = 653
	Rooms[122].Connection[47] = 123
	Rooms[122].Connection[41] = 233660
	Rooms[122].Connection[49] = 233660
	Rooms[122].Connection[69] = 233660
	Rooms[122].Connection[42] = 233660
	Rooms[122].Connection[41] = 303
	Rooms[122].Connection[39] = 596
	Rooms[122].Connection[77] = 124
	Rooms[122].Connection[28] = 126
	Rooms[122].Connection[40] = 129
	Rooms[123].Connection[44] = 122
	Rooms[123].Connection[43] = 124
	Rooms[123].Connection[77] = 124
	Rooms[123].Connection[28] = 126
	Rooms[123].Connection[40] = 129
	Rooms[124].Connection[44] = 123
	Rooms[124].Connection[47] = 125
	Rooms[124].Connection[36] = 125
	Rooms[124].Connection[48] = 128
	Rooms[124].Connection[30] = 128
	Rooms[124].Connection[37] = 128
	Rooms[124].Connection[28] = 126
	Rooms[124].Connection[40] = 129
	Rooms[125].Connection[46] = 124
	Rooms[125].Connection[77] = 124
	Rooms[125].Connection[45] = 126
	Rooms[125].Connection[28] = 126
	Rooms[125].Connection[43] = 127
	Rooms[125].Connection[17] = 127
	Rooms[126].Connection[46] = 125
	Rooms[126].Connection[11] = 125
	Rooms[126].Connection[23] = 125
	Rooms[126].Connection[77] = 124
	Rooms[126].Connection[30] = 610
	Rooms[126].Connection[39] = 610
	Rooms[127].Connection[44] = 125
	Rooms[127].Connection[17] = 125
	Rooms[127].Connection[11] = 125
	Rooms[127].Connection[77] = 124
	Rooms[127].Connection[28] = 126
	Rooms[128].Connection[45] = 124
	Rooms[128].Connection[77] = 124
	Rooms[128].Connection[29] = 124
	Rooms[128].Connection[46] = 129
	Rooms[128].Connection[40] = 129
	Rooms[128].Connection[30] = 129
	Rooms[128].Connection[28] = 126
	Rooms[129].Connection[44] = 128
	Rooms[129].Connection[29] = 128
	Rooms[129].Connection[77] = 124
	Rooms[129].Connection[43] = 130
	Rooms[129].Connection[3] = 130
	Rooms[129].Connection[40] = 130
	Rooms[129].Connection[19] = 130
	Rooms[129].Connection[28] = 126
	Rooms[130].Connection[44] = 129
	Rooms[130].Connection[11] = 129
	Rooms[130].Connection[77] = 124
	Rooms[130].Connection[28] = 126
	Rooms[131].Connection[44] = 107
	Rooms[131].Connection[48] = 132
	Rooms[131].Connection[50] = 133
	Rooms[131].Connection[49] = 134
	Rooms[131].Connection[47] = 135
	Rooms[131].Connection[29] = 136
	Rooms[131].Connection[30] = 137
	Rooms[131].Connection[45] = 138
	Rooms[131].Connection[46] = 139
	Rooms[131].Connection[43] = 112
	Rooms[132].Connection[50] = 107
	Rooms[132].Connection[29] = 131
	Rooms[132].Connection[45] = 133
	Rooms[132].Connection[46] = 134
	Rooms[132].Connection[44] = 135
	Rooms[132].Connection[49] = 136
	Rooms[132].Connection[47] = 137
	Rooms[132].Connection[43] = 138
	Rooms[132].Connection[30] = 139
	Rooms[132].Connection[48] = 112
	Rooms[133].Connection[29] = 107
	Rooms[133].Connection[30] = 131
	Rooms[133].Connection[44] = 132
	Rooms[133].Connection[47] = 134
	Rooms[133].Connection[49] = 135
	Rooms[133].Connection[43] = 136
	Rooms[133].Connection[45] = 137
	Rooms[133].Connection[50] = 138
	Rooms[133].Connection[48] = 139
	Rooms[133].Connection[46] = 112
	Rooms[134].Connection[47] = 107
	Rooms[134].Connection[45] = 131
	Rooms[134].Connection[50] = 132
	Rooms[134].Connection[48] = 133
	Rooms[134].Connection[43] = 135
	Rooms[134].Connection[30] = 136
	Rooms[134].Connection[46] = 137
	Rooms[134].Connection[29] = 138
	Rooms[134].Connection[44] = 139
	Rooms[134].Connection[49] = 112
	Rooms[135].Connection[45] = 107
	Rooms[135].Connection[48] = 131
	Rooms[135].Connection[30] = 132
	Rooms[135].Connection[46] = 133
	Rooms[135].Connection[43] = 134
	Rooms[135].Connection[44] = 136
	Rooms[135].Connection[49] = 137
	Rooms[135].Connection[47] = 138
	Rooms[135].Connection[50] = 139
	Rooms[135].Connection[29] = 112
	Rooms[136].Connection[43] = 107
	Rooms[136].Connection[44] = 131
	Rooms[136].Connection[29] = 132
	Rooms[136].Connection[49] = 133
	Rooms[136].Connection[30] = 134
	Rooms[136].Connection[46] = 135
	Rooms[136].Connection[50] = 137
	Rooms[136].Connection[48] = 138
	Rooms[136].Connection[47] = 139
	Rooms[136].Connection[45] = 112
	Rooms[137].Connection[48] = 107
	Rooms[137].Connection[47] = 131
	Rooms[137].Connection[46] = 132
	Rooms[137].Connection[30] = 133
	Rooms[137].Connection[29] = 134
	Rooms[137].Connection[50] = 135
	Rooms[137].Connection[45] = 136
	Rooms[137].Connection[49] = 138
	Rooms[137].Connection[43] = 139
	Rooms[137].Connection[44] = 112
	Rooms[138].Connection[30] = 107
	Rooms[138].Connection[43] = 131
	Rooms[138].Connection[47] = 132
	Rooms[138].Connection[29] = 133
	Rooms[138].Connection[44] = 134
	Rooms[138].Connection[45] = 135
	Rooms[138].Connection[46] = 136
	Rooms[138].Connection[48] = 137
	Rooms[138].Connection[49] = 139
	Rooms[138].Connection[50] = 112
	Rooms[139].Connection[49] = 107
	Rooms[139].Connection[50] = 131
	Rooms[139].Connection[43] = 132
	Rooms[139].Connection[44] = 133
	Rooms[139].Connection[45] = 134
	Rooms[139].Connection[30] = 135
	Rooms[139].Connection[48] = 136
	Rooms[139].Connection[29] = 137
	Rooms[139].Connection[46] = 138
	Rooms[139].Connection[47] = 112
	Rooms[140].Connection[45] = 112
	Rooms[140].Connection[11] = 112
}

type Object struct {
	Id          int
	Keywords    []string
	Name        string
	Description map[int]string
	Location    int
	AltLocation int
	Immovable   bool
}

var Objects = make(map[int]*Object)

func LoadObjects() {
	for i := 1001; i <= 1070; i++ {
		Objects[i] = &Object{}
		Objects[i].Description = make(map[int]string)
	}
	Objects[1001].Keywords = []string{`KEYS`, `KEY`}
	Objects[1001].Id = 1001
	Objects[1001].Name = "SET OF KEYS"
	Objects[1001].Description[000] = `THERE ARE SOME KEYS ON THE GROUND HERE.`
	Objects[1002].Keywords = []string{`LAMP`, `HEADL`, `LANTE`}
	Objects[1002].Id = 1002
	Objects[1002].Name = "BRASS LANTERN"
	Objects[1002].Description[000] = `THERE IS A SHINY BRASS LAMP NEARBY.`
	Objects[1002].Description[100] = `THERE IS A LAMP SHINING NEARBY.`
	Objects[1003].Keywords = []string{`GRATE`}
	Objects[1003].Id = 1003
	Objects[1003].Name = "*GRATE"
	Objects[1003].Description[000] = `THE GRATE IS LOCKED.`
	Objects[1003].Description[100] = `THE GRATE IS OPEN.`
	Objects[1004].Keywords = []string{`CAGE`}
	Objects[1004].Id = 1004
	Objects[1004].Name = "WICKER CAGE"
	Objects[1004].Description[000] = `THERE IS A SMALL WICKER CAGE DISCARDED NEARBY.`
	Objects[1005].Keywords = []string{`ROD`}
	Objects[1005].Id = 1005
	Objects[1005].Name = "BLACK ROD"
	Objects[1005].Description[000] = `A THREE FOOT BLACK ROD WITH A RUSTY STAR ON AN END LIES NEARBY.`
	Objects[1006].Keywords = []string{`ROD`} // (MUST BE NEXT OBJECT AFTER "REAL" ROD)`
	Objects[1006].Id = 1006
	Objects[1006].Name = "BLACK ROD"
	Objects[1006].Description[000] = `A THREE FOOT BLACK ROD WITH A RUSTY MARK ON AN END LIES NEARBY.`
	Objects[1007].Keywords = []string{`STEPS`}
	Objects[1007].Id = 1007
	Objects[1007].Name = "*STEPS"
	Objects[1007].Description[000] = `ROUGH STONE STEPS LEAD DOWN THE PIT.`
	Objects[1007].Description[100] = `ROUGH STONE STEPS LEAD UP THE DOME.`
	Objects[1008].Keywords = []string{`BIRD`}
	Objects[1008].Id = 1008
	Objects[1008].Name = "LITTLE BIRD IN CAGE"
	Objects[1008].Description[000] = `A CHEERFUL LITTLE BIRD IS SITTING HERE SINGING.`
	Objects[1008].Description[100] = `THERE IS A LITTLE BIRD IN THE CAGE.`
	Objects[1009].Keywords = []string{`DOOR`}
	Objects[1009].Id = 1009
	Objects[1009].Name = "*RUSTY DOOR"
	Objects[1009].Description[000] = `THE WAY NORTH IS BARRED BY A MASSIVE, RUSTY, IRON DOOR.`
	Objects[1009].Description[100] = `THE WAY NORTH LEADS THROUGH A MASSIVE, RUSTY, IRON DOOR.`
	Objects[1010].Keywords = []string{`PILLO`, `VELVE`}
	Objects[1010].Id = 1010
	Objects[1010].Name = "VELVET PILLOW"
	Objects[1010].Description[000] = `A SMALL VELVET PILLOW LIES ON THE FLOOR.`
	Objects[1011].Keywords = []string{`SNAKE`}
	Objects[1011].Id = 1011
	Objects[1011].Name = "*SNAKE"
	Objects[1011].Description[000] = `A HUGE GREEN FIERCE SNAKE BARS THE WAY!`
	Objects[1011].Description[100] = `>$. (CHASED AWAY)`
	Objects[1012].Keywords = []string{`FISSU`}
	Objects[1012].Id = 1012
	Objects[1012].Name = "*FISSURE"
	Objects[1012].Description[000] = `>$<`
	Objects[1012].Description[100] = `A CRYSTAL BRIDGE NOW SPANS THE FISSURE.`
	Objects[1012].Description[200] = `THE CRYSTAL BRIDGE HAS VANISHED!`
	Objects[1013].Keywords = []string{`TABLE`}
	Objects[1013].Id = 1013
	Objects[1013].Name = "*STONE TABLET"
	Objects[1013].Description[000] = `A MASSIVE STONE TABLET IMBEDDED IN THE WALL READS, "CONGRATULATIONS ON BRINGING LIGHT INTO THE DARK-ROOM!"`
	Objects[1014].Keywords = []string{`CLAM`}
	Objects[1014].Id = 1014
	Objects[1014].Name = "GIANT CLA. >GRUNT!<"
	Objects[1014].Description[000] = `THERE IS AN ENORMOUS CLAM HERE WITH ITS SHELL TIGHTLY CLOSED.`
	Objects[1015].Keywords = []string{`OYSTE`}
	Objects[1015].Id = 1015
	Objects[1015].Name = "GIANT OYSTE. >GROAN!<"
	Objects[1015].Description[000] = `THERE IS AN ENORMOUS OYSTER HERE WITH ITS SHELL TIGHTLY CLOSED.`
	Objects[1015].Description[100] = `INTERESTING. THERE SEEMS TO BE SOMETHING WRITTEN ON THE UNDERSIDE OF THE OYSTER.`
	Objects[1016].Keywords = []string{`MAGAZ`, `ISSUE`, `SPELU`, `"SPEL`}
	Objects[1016].Id = 1016
	Objects[1016].Name = `"SPELUNKER TODAY"`
	Objects[1016].Description[000] = `THERE ARE A FEW RECENT ISSUES OF "SPELUNKER TODAY" MAGAZINE HERE.`
	Objects[1019].Keywords = []string{`FOOD`, `RATIO`}
	Objects[1019].Id = 1019
	Objects[1019].Name = "TASTY FOOD"
	Objects[1019].Description[000] = `THERE IS FOOD HERE.`
	Objects[1020].Keywords = []string{`BOTTL`, `JAR`}
	Objects[1020].Id = 1020
	Objects[1020].Name = "SMALL BOTTLE"
	Objects[1020].Description[000] = `THERE IS A BOTTLE OF WATER HERE.`
	Objects[1020].Description[100] = `THERE IS AN EMPTY BOTTLE HERE.`
	Objects[1020].Description[200] = `THERE IS A BOTTLE OF OIL HERE.`
	Objects[1023].Keywords = []string{`MIRRO`}
	Objects[1023].Id = 1023
	Objects[1023].Name = "*MIRROR"
	Objects[1023].Description[000] = `>$<`
	Objects[1024].Keywords = []string{`PLANT`, `BEANS`}
	Objects[1024].Id = 1024
	Objects[1024].Name = "*PLANT"
	Objects[1024].Description[000] = `THERE IS A TINY LITTLE PLANT IN THE PIT, MURMURING "WATER, WATER..."`
	Objects[1024].Description[100] = `THE PLANT SPURTS INTO FURIOUS GROWTH FOR A FEW SECONDS.`
	Objects[1024].Description[200] = `THERE IS A 12-FOOT-TALL BEANSTALK STRETCHING UP OUT OF THE PIT, BELLOWING "WATER!! WATER!!"`
	Objects[1024].Description[300] = `THE PLANT GROWS EXPLOSIVELY, ALMOST FILLING THE BOTTOM OF THE PIT.`
	Objects[1024].Description[400] = `THERE IS A GIGANTIC BEANSTALK STRETCHING ALL THE WAY UP TO THE HOLE.`
	Objects[1024].Description[500] = `YOU'VE OVER-WATERED THE PLANT! IT'S SHRIVELING UP. IT'S, IT'S...`
	Objects[1025].Keywords = []string{`PLANT`} //(MUST BE NEXT OBJECT AFTER "REAL" PLANT)`
	Objects[1025].Id = 1025
	Objects[1025].Name = "*PHONY PLANT (SEEN IN TWOPIT ROOM ONLY WHEN TALL ENOUGH)"
	Objects[1025].Description[000] = `>$<`
	Objects[1025].Description[100] = `THE TOP OF A 12-FOOT-TALL BEANSTALK IS POKING OUT OF THE WEST PIT.`
	Objects[1025].Description[200] = `THERE IS A HUGE BEANSTALK GROWING OUT OF THE WEST PIT UP TO THE HOLE.`
	Objects[1026].Keywords = []string{`STALA`}
	Objects[1026].Id = 1026
	Objects[1026].Name = "*STALACTITE"
	Objects[1026].Description[000] = `>$<`
	Objects[1027].Keywords = []string{`SHADO`, `FIGUR`}
	Objects[1027].Id = 1027
	Objects[1027].Name = "*SHADOWY FIGURE"
	Objects[1027].Description[000] = `THE SHADOWY FIGURE SEEMS TO BE TRYING TO ATTRACT YOUR ATTENTION.`
	Objects[1028].Keywords = []string{`AXE`}
	Objects[1028].Id = 1028
	Objects[1028].Name = "DWARF'S AXE"
	Objects[1028].Description[000] = `THERE IS A LITTLE AXE HERE.`
	Objects[1028].Description[100] = `THERE IS A LITTLE AXE LYING BESIDE THE BEAR.`
	Objects[1029].Keywords = []string{`DRAWI`}
	Objects[1029].Id = 1029
	Objects[1029].Name = "*CAVE DRAWINGS"
	Objects[1029].Description[000] = `>$<`
	Objects[1030].Keywords = []string{`PIRAT`}
	Objects[1030].Id = 1030
	Objects[1030].Name = "*PIRATE"
	Objects[1030].Description[000] = `>$<`
	Objects[1031].Keywords = []string{`DRAGO`}
	Objects[1031].Id = 1031
	Objects[1031].Name = "*DRAGON"
	Objects[1031].Description[000] = `A HUGE GREEN FIERCE DRAGON BARS THE WAY!`
	Objects[1031].Description[100] = `CONGRATULATIONS. YOU HAVE JUST VANQUISHED A DRAGON WITH YOUR BARE HANDS! (UNBELIEVABLE, ISN'T IT?)`
	Objects[1031].Description[200] = `THE BODY OF A HUGE GREEN DEAD DRAGON IS LYING OFF TO ONE SIDE.`
	Objects[1032].Keywords = []string{`CHASM`}
	Objects[1032].Id = 1032
	Objects[1032].Name = "*CHASM"
	Objects[1032].Description[000] = `A RICKETY WOODEN BRIDGE EXTENDS ACROSS THE CHASM, VANISHING INTO THE MIST. A SIGN POSTED ON THE BRIDGE READS, "STOP! PAY TROLL!"`
	Objects[1032].Description[100] = `THE WRECKAGE OF A BRIDGE (AND A DEAD BEAR) CAN BE SEEN AT THE BOTTOM OF THE CHASM.`
	Objects[1033].Keywords = []string{`TROLL`}
	Objects[1033].Id = 1033
	Objects[1033].Name = "*TROLL"
	Objects[1033].Description[000] = `A BURLY TROLL STANDS BY THE BRIDGE AND INSISTS YOU THROW HIM A TREASURE BEFORE YOU MAY CROSS.`
	Objects[1033].Description[100] = `THE TROLL STEPS OUT FROM BENEATH THE BRIDGE AND BLOCKS YOUR WAY.`
	Objects[1033].Description[200] = `>$. (CHASED AWAY)`
	Objects[1034].Keywords = []string{`TROLL`} // (MUST BE NEXT OBJECT AFTER "REAL" TROLL)`
	Objects[1034].Id = 1034
	Objects[1034].Name = "*PHONY TROLL"
	Objects[1034].Description[000] = `THE TROLL IS NOWHERE TO BE SEEN.`
	Objects[1035].Keywords = []string{`BEAR`}
	Objects[1035].Id = 1035
	Objects[1035].Name = ">$. (BEAR USES RTEXT 141)"
	Objects[1035].Description[000] = `THERE IS A FEROCIOUS CAVE BEAR EYING YOU FROM THE FAR END OF THE ROOM!`
	Objects[1035].Description[100] = `THERE IS A GENTLE CAVE BEAR SITTING PLACIDLY IN ONE CORNER.`
	Objects[1035].Description[200] = `THERE IS A CONTENTED-LOOKING BEAR WANDERING ABOUT NEARBY.`
	Objects[1035].Description[300] = `>$. (DEAD)`
	Objects[1036].Keywords = []string{`MESSA`}
	Objects[1036].Id = 1036
	Objects[1036].Name = "*MESSAGE IN SECOND MAZE"
	Objects[1036].Description[000] = `THERE IS A MESSAGE SCRAWLED IN THE DUST IN A FLOWERY SCRIPT, READING: "THIS IS NOT THE MAZE WHERE THE PIRATE LEAVES HIS TREASURE CHEST."`
	Objects[1037].Keywords = []string{`VOLCA`, `GEYSE`} // (SAME AS VOLCANO)`
	Objects[1037].Id = 1037
	Objects[1037].Name = "*VOLCANO AND/OR GEYSER"
	Objects[1037].Description[000] = `>$<`
	Objects[1038].Keywords = []string{`MACHI`, `VENDI`}
	Objects[1038].Id = 1038
	Objects[1038].Name = "*VENDING MACHINE"
	Objects[1038].Description[000] = `THERE IS A MASSIVE VENDING MACHINE HERE. THE INSTRUCTIONS ON IT READ: "DROP COINS HERE TO RECEIVE FRESH BATTERIES."`
	Objects[1039].Keywords = []string{`BATTE`}
	Objects[1039].Id = 1039
	Objects[1039].Name = "BATTERIES"
	Objects[1039].Description[000] = `THERE ARE FRESH BATTERIES HERE.`
	Objects[1039].Description[100] = `SOME WORN-OUT BATTERIES HAVE BEEN DISCARDED NEARBY.`
	Objects[1040].Keywords = []string{`CARPE`, `MOSS`}
	Objects[1040].Id = 1040
	Objects[1040].Name = "*CARPET AND/OR MOSS"
	Objects[1040].Description[000] = `>$<`
	Objects[1050].Keywords = []string{`GOLD`, `NUGGE`}
	Objects[1050].Id = 1050
	Objects[1050].Name = "LARGE GOLD NUGGET"
	Objects[1050].Description[000] = `THERE IS A LARGE SPARKLING NUGGET OF GOLD HERE!`
	Objects[1051].Keywords = []string{`DIAMO`}
	Objects[1051].Id = 1051
	Objects[1051].Name = "SEVERAL DIAMONDS"
	Objects[1051].Description[000] = `THERE ARE DIAMONDS HERE!`
	Objects[1052].Keywords = []string{`SILVE`, `BARS`}
	Objects[1052].Id = 1052
	Objects[1052].Name = "BARS OF SILVER"
	Objects[1052].Description[000] = `THERE ARE BARS OF SILVER HERE!`
	Objects[1053].Keywords = []string{`JEWEL`}
	Objects[1053].Id = 1053
	Objects[1053].Name = "PRECIOUS JEWELRY"
	Objects[1053].Description[000] = `THERE IS PRECIOUS JEWELRY HERE!`
	Objects[1054].Keywords = []string{`COINS`}
	Objects[1054].Id = 1054
	Objects[1054].Name = "RARE COINS"
	Objects[1054].Description[000] = `THERE ARE MANY COINS HERE!`
	Objects[1055].Keywords = []string{`CHEST`, `BOX`, `TREAS`}
	Objects[1055].Id = 1055
	Objects[1055].Name = "TREASURE CHEST"
	Objects[1055].Description[000] = `THE PIRATE'S TREASURE CHEST IS HERE!`
	Objects[1056].Keywords = []string{`EGGS`, `EGG`, `NEST`}
	Objects[1056].Id = 1056
	Objects[1056].Name = "GOLDEN EGGS"
	Objects[1056].Description[000] = `THERE IS A LARGE NEST HERE, FULL OF GOLDEN EGGS!`
	Objects[1056].Description[100] = `THE NEST OF GOLDEN EGGS HAS VANISHED!`
	Objects[1056].Description[200] = `DONE!`
	Objects[1057].Keywords = []string{`TRIDE`}
	Objects[1057].Id = 1057
	Objects[1057].Name = "JEWELED TRIDENT"
	Objects[1057].Description[000] = `THERE IS A JEWEL-ENCRUSTED TRIDENT HERE!`
	Objects[1058].Keywords = []string{`VASE`, `MING`, `SHARD`, `POTTE`}
	Objects[1058].Id = 1058
	Objects[1058].Name = "MING VASE"
	Objects[1058].Description[000] = `THERE IS A DELICATE, PRECIOUS, MING VASE HERE!`
	Objects[1058].Description[100] = `THE VASE IS NOW RESTING, DELICATELY, ON A VELVET PILLOW.`
	Objects[1058].Description[200] = `THE FLOOR IS LITTERED WITH WORTHLESS SHARDS OF POTTERY.`
	Objects[1058].Description[300] = `THE MING VASE DROPS WITH A DELICATE CRASH.`
	Objects[1059].Keywords = []string{`EMERA`}
	Objects[1059].Id = 1059
	Objects[1059].Name = "EGG-SIZED EMERALD"
	Objects[1059].Description[000] = `THERE IS AN EMERALD HERE THE SIZE OF A PLOVER'S EGG!`
	Objects[1060].Keywords = []string{`PLATI`, `PYRAM`}
	Objects[1060].Id = 1060
	Objects[1060].Name = "PLATINUM PYRAMID"
	Objects[1060].Description[000] = `THERE IS A PLATINUM PYRAMID HERE, 8 INCHES ON A SIDE!`
	Objects[1061].Keywords = []string{`PEARL`}
	Objects[1061].Id = 1061
	Objects[1061].Name = "GLISTENING PEARL"
	Objects[1061].Description[000] = `OFF TO ONE SIDE LIES A GLISTENING PEARL!`
	Objects[1062].Keywords = []string{`RUG`, `PERSI`}
	Objects[1062].Id = 1062
	Objects[1062].Name = "PERSIAN RUG"
	Objects[1062].Description[000] = `THERE IS A PERSIAN RUG SPREAD OUT ON THE FLOOR!`
	Objects[1062].Description[100] = `THE DRAGON IS SPRAWLED OUT ON A PERSIAN RUG!!`
	Objects[1063].Keywords = []string{`SPICE`}
	Objects[1063].Id = 1063
	Objects[1063].Name = "RARE SPICES"
	Objects[1063].Description[000] = `THERE ARE RARE SPICES HERE!`
	Objects[1064].Keywords = []string{`CHAIN`}
	Objects[1064].Id = 1064
	Objects[1064].Name = "GOLDEN CHAIN"
	Objects[1064].Description[000] = `THERE IS A GOLDEN CHAIN LYING IN A HEAP ON THE FLOOR!`
	Objects[1064].Description[100] = `THE BEAR IS LOCKED TO THE WALL WITH A GOLDEN CHAIN!`
	Objects[1064].Description[200] = `THERE IS A GOLDEN CHAIN LOCKED TO THE WALL!`

	Objects[1017] = &Object{
		Keywords: []string{`DWARF`, `DWARV`},
		Id:       1017,
	}
	Objects[1018] = &Object{
		Keywords: []string{`KNIFE`, `KNIVE`},
		Id:       1018,
	}
	Objects[1021] = &Object{
		Keywords: []string{`WATER`, `H2O`},
		Id:       1021,
		Name:     "WATER IN THE BOTTLE",
	}
	Objects[1022] = &Object{
		Keywords: []string{`OIL`},
		Id:       1022,
		Name:     "OIL IN THE BOTTLE",
	}
}

func LoadMessages() {
    // various response messages
	Msgs[1] = `SOMEWHERE NEARBY IS COLOSSAL CAVE, WHERE OTHERS HAVE FOUND FORTUNES IN TREASURE AND GOLD, THOUGH IT IS RUMORED THAT SOME WHO ENTER ARE NEVER SEEN AGAIN. MAGIC IS SAID TO WORK IN THE CAVE. I WILL BE YOUR EYES AND HANDS. DIRECT ME WITH COMMANDS OF 1 OR 2 WORDS. I SHOULD WARN YOU THAT I LOOK AT ONLY THE FIRST FIVE LETTERS OF EACH WORD, SO YOU'LL HAVE TO ENTER "NORTHEAST" AS "NE" TO DISTINGUISH IT FROM "NORTH". (SHOULD YOU GET STUCK, TYPE "HELP" FOR SOME GENERAL HINTS. FOR INFORMATION ON HOW TO END YOUR ADVENTURE, ETC., TYPE "INFO".)`
	Msgs[2] = `A LITTLE DWARF WITH A BIG KNIFE BLOCKS YOUR WAY.`
	Msgs[3] = `A LITTLE DWARF JUST WALKED AROUND A CORNER, SAW YOU, THREW A LITTLE AXE AT YOU WHICH MISSED, CURSED, AND RAN AWAY.`
	Msgs[4] = `THERE IS A THREATENING LITTLE DWARF IN THE ROOM WITH YOU!`
	Msgs[5] = `ONE SHARP NASTY KNIFE IS THROWN AT YOU!`
	Msgs[6] = `NONE OF THEM HIT YOU!`
	Msgs[7] = `ONE OF THEM GETS YOU!`
	Msgs[8] = `A HOLLOW VOICE SAYS "PLUGH".`
	Msgs[9] = `THERE IS NO WAY TO GO THAT DIRECTION.`
	Msgs[10] = `I AM UNSURE HOW YOU ARE FACING. USE COMPASS POINTS OR NEARBY OBJECTS.`
	Msgs[11] = `I DON'T KNOW IN FROM OUT HERE. USE COMPASS POINTS OR NAME SOMETHING`
	Msgs[11] = `IN THE GENERAL DIRECTION YOU WANT TO GO.`
	Msgs[12] = `I DON'T KNOW HOW TO APPLY THAT WORD HERE.`
	Msgs[13] = `I DON'T UNDERSTAND THAT!`
	Msgs[14] = `I'M GAME. WOULD YOU CARE TO EXPLAIN HOW?`
	Msgs[15] = `SORRY, BUT I AM NOT ALLOWED TO GIVE MORE DETAIL. I WILL REPEAT THE`
	Msgs[15] = `LONG DESCRIPTION OF YOUR LOCATION.`
	Msgs[16] = `IT IS NOW PITCH DARK. IF YOU PROCEED YOU WILL LIKELY FALL INTO A PIT.`
	Msgs[17] = `IF YOU PREFER, SIMPLY TYPE W RATHER THAN WEST.`
	Msgs[18] = `ARE YOU TRYING TO CATCH THE BIRD?`
	Msgs[19] = `THE BIRD IS FRIGHTENED RIGHT NOW AND YOU CANNOT CATCH IT NO MATTER WHAT YOU TRY. PERHAPS YOU MIGHT TRY LATER.`
	Msgs[20] = `ARE YOU TRYING TO SOMEHOW DEAL WITH THE SNAKE?`
	Msgs[21] = `YOU CAN'T KILL THE SNAKE, OR DRIVE IT AWAY, OR AVOID IT, OR ANYTHING LIKE THAT. THERE IS A WAY TO GET BY, BUT YOU DON'T HAVE THE NECESSARY RESOURCES RIGHT NOW.`
	Msgs[22] = `DO YOU REALLY WANT TO QUIT NOW?`
	Msgs[23] = `YOU FELL INTO A PIT AND BROKE EVERY BONE IN YOUR BODY!`
	Msgs[24] = `YOU ARE ALREADY CARRYING IT!`
	Msgs[25] = `YOU CAN'T BE SERIOUS!`
	Msgs[26] = `THE BIRD WAS UNAFRAID WHEN YOU ENTERED, BUT AS YOU APPROACH IT BECOMES DISTURBED AND YOU CANNOT CATCH IT.`
	Msgs[27] = `YOU CAN CATCH THE BIRD, BUT YOU CANNOT CARRY IT.`
	Msgs[28] = `THERE IS NOTHING HERE WITH A LOCK!`
	Msgs[29] = `YOU AREN'T CARRYING IT!`
	Msgs[30] = `THE LITTLE BIRD ATTACKS THE GREEN SNAKE, AND IN AN ASTOUNDING FLURRY DRIVES THE SNAKE AWAY.`
	Msgs[31] = `YOU HAVE NO KEYS!`
	Msgs[32] = `IT HAS NO LOCK.`
	Msgs[33] = `I DON'T KNOW HOW TO LOCK OR UNLOCK SUCH A THING.`
	Msgs[34] = `IT WAS ALREADY LOCKED.`
	Msgs[35] = `THE GRATE IS NOW LOCKED.`
	Msgs[36] = `THE GRATE IS NOW UNLOCKED.`
	Msgs[37] = `IT WAS ALREADY UNLOCKED.`
	Msgs[38] = `YOU HAVE NO SOURCE OF LIGHT.`
	Msgs[39] = `YOUR LAMP IS NOW ON.`
	Msgs[40] = `YOUR LAMP IS NOW OFF.`
	Msgs[41] = `THERE IS NO WAY TO GET PAST THE BEAR TO UNLOCK THE CHAIN, WHICH IS PROBABLY JUST AS WELL.`
	Msgs[42] = `NOTHING HAPPENS.`
	Msgs[43] = `WHERE?`
	Msgs[44] = `THERE IS NOTHING HERE TO ATTACK.`
	Msgs[45] = `THE LITTLE BIRD IS NOW DEAD. ITS BODY DISAPPEARS.`
	Msgs[46] = `ATTACKING THE SNAKE BOTH DOESN'T WORK AND IS VERY DANGEROUS.`
	Msgs[47] = `YOU KILLED A LITTLE DWARF.`
	Msgs[48] = `YOU ATTACK A LITTLE DWARF, BUT HE DODGES OUT OF THE WAY.`
	Msgs[49] = `WITH WHAT. YOUR BARE HANDS?`
	Msgs[50] = `GOOD TRY, BUT THAT IS AN OLD WORN-OUT MAGIC WORD.`
	Msgs[51] = `I KNOW OF PLACES, ACTIONS, AND THINGS. MOST OF MY VOCABULARY DESCRIBES PLACES AND IS USED TO MOVE YOU THERE. TO MOVE, TRY WORDS LIKE FOREST, BUILDING, DOWNSTREAM, ENTER, EAST, WEST, NORTH, SOUTH, UP, OR DOWN. I KNOW ABOUT A FEW SPECIAL OBJECTS, LIKE A BLACK ROD HIDDEN IN THE CAVE. THESE OBJECTS CAN BE MANIPULATED USING SOME OF THE ACTION WORDS THAT I KNOW. USUALLY YOU WILL NEED TO GIVE BOTH THE OBJECT AND ACTION WORDS (IN EITHER ORDER), BUT SOMETIMES I CAN INFER THE OBJECT FROM THE VERB ALONE. SOME OBJECTS ALSO IMPLY VERBS; IN PARTICULAR, "INVENTORY" IMPLIES "TAKE INVENTORY", WHICH CAUSES ME TO GIVE YOU A LIST OF WHAT YOU'RE CARRYING. THE OBJECTS HAVE SIDE EFFECTS; FOR INSTANCE, THE ROD SCARES THE BIRD. USUALLY PEOPLE HAVING TROUBLE MOVING JUST NEED TO TRY A FEW MORE WORDS. USUALLY PEOPLE TRYING UNSUCCESSFULLY TO MANIPULATE AN OBJECT ARE ATTEMPTING SOMETHING BEYOND THEIR (OR MY!) CAPABILITIES AND SHOULD TRY A COMPLETELY DIFFERENT TACK. TO SPEED THE GAME YOU CAN SOMETIMES MOVE LONG DISTANCES WITH A SINGLE WORD. FOR EXAMPLE, "BUILDING" USUALLY GETS YOU TO THE BUILDING FROM ANYWHERE ABOVE GROUND EXCEPT WHEN LOST IN THE FOREST. ALSO, NOTE THAT CAVE PASSAGES TURN A LOT, AND THAT LEAVING A ROOM TO THE NORTH DOES NOT GUARANTEE ENTERING THE NEXT FROM THE SOUTH. GOOD LUCK!`
	Msgs[52] = `IT MISSES!`
	Msgs[53] = `IT GETS YOU!`
	Msgs[54] = `OK`
	Msgs[55] = `YOU CAN'T UNLOCK THE KEYS.`
	Msgs[56] = `YOU HAVE CRAWLED AROUND IN SOME LITTLE HOLES AND WOUND UP BACK IN THE MAIN PASSAGE.`
	Msgs[57] = `I DON'T KNOW WHERE THE CAVE IS, BUT HEREABOUTS NO STREAM CAN RUN ON THE SURFACE FOR LONG. I WOULD TRY THE STREAM.`
	Msgs[58] = `I NEED MORE DETAILED INSTRUCTIONS TO DO THAT.`
	Msgs[59] = `I CAN ONLY TELL YOU WHAT YOU SEE AS YOU MOVE ABOUT AND MANIPULATE THINGS. I CANNOT TELL YOU WHERE REMOTE THINGS ARE.`
	Msgs[60] = `I DON'T KNOW THAT WORD.`
	Msgs[61] = `WHAT?`
	Msgs[62] = `ARE YOU TRYING TO GET INTO THE CAVE?`
	Msgs[63] = `THE GRATE IS VERY SOLID AND HAS A HARDENED STEEL LOCK. YOU CANNOT ENTER WITHOUT A KEY, AND THERE ARE NO KEYS NEARBY. I WOULD RECOMMEND LOOKING ELSEWHERE FOR THE KEYS.`
	Msgs[64] = `THE TREES OF THE FOREST ARE LARGE HARDWOOD OAK AND MAPLE, WITH AN OCCASIONAL GROVE OF PINE OR SPRUCE. THERE IS QUITE A BIT OF UNDER- GROWTH, LARGELY BIRCH AND ASH SAPLINGS PLUS NONDESCRIPT BUSHES OF VARIOUS SORTS. THIS TIME OF YEAR VISIBILITY IS QUITE RESTRICTED BY ALL THE LEAVES, BUT TRAVEL IS QUITE EASY IF YOU DETOUR AROUND THE SPRUCE AND BERRY BUSHES.`
	Msgs[65] = `WELCOME TO ADVENTURE!! WOULD YOU LIKE INSTRUCTIONS?`
	Msgs[66] = `DDIGGING WITHOUT A SHOVEL IS QUITE IMPRACTICAL. EVEN WITH A SHOVEL PROGRESS IS UNLIKELY.`
	Msgs[67] = `BLASTING REQUIRES DYNAMITE.`
	Msgs[68] = `I'M AS CONFUSED AS YOU ARE.`
	Msgs[69] = `MIST IS A WHITE VAPOR, USUALLY WATER, SEEN FROM TIME TO TIME IN CAVERNS. IT CAN BE FOUND ANYWHERE BUT IS FREQUENTLY A SIGN OF A DEEP PIT LEADING DOWN TO WATER.`
	Msgs[70] = `YOUR FEET ARE NOW WET.`
	Msgs[71] = `I THINK I JUST LOST MY APPETITE.`
	Msgs[72] = `THANK YOU, IT WAS DELICIOUS!`
	Msgs[73] = `YOU HAVE TAKEN A DRINK FROM THE STREAM. THE WATER TASTES STRONGLY OF MINERALS, BUT IS NOT UNPLEASANT. IT IS EXTREMELY COLD.`
	Msgs[74] = `THE BOTTLE OF WATER IS NOW EMPTY.`
	Msgs[75] = `RUBBING THE ELECTRIC LAMP IS NOT PARTICULARLY REWARDING. ANYWAY, NOTHING EXCITING HAPPENS.`
	Msgs[76] = `PECULIAR. NOTHING UNEXPECTED HAPPENS.`
	Msgs[77] = `YOUR BOTTLE IS EMPTY AND THE GROUND IS WET.`
	Msgs[78] = `YOU CAN'T POUR THAT.`
	Msgs[79] = `WATCH IT!`
	Msgs[80] = `WHICH WAY?`
	Msgs[81] = `OH DEAR, YOU SEEM TO HAVE GOTTEN YOURSELF KILLED. I MIGHT BE ABLE TO HELP YOU OUT, BUT I'VE NEVER REALLY DONE THIS BEFORE. DO YOU WANT ME TO TRY TO REINCARNATE YOU?`
	Msgs[82] = `ALL RIGHT. BUT DON'T BLAME ME IF SOMETHING GOES WR...... . --- POOF!! --- YOU ARE ENGULFED IN A CLOUD OF ORANGE SMOKE. COUGHING AND GASPING, YOU EMERGE FROM THE SMOKE AND FIND....`
	Msgs[83] = `YOU CLUMSY OAF, YOU'VE DONE IT AGAIN. I DON'T KNOW HOW LONG I CAN KEEP THIS UP. DO YOU WANT ME TO TRY REINCARNATING YOU AGAIN?`
	Msgs[84] = `OKAY, NOW WHERE DID I PUT MY ORANGE SMOKE?.... >POOF!< EVERYTHING DISAPPEARS IN A DENSE CLOUD OF ORANGE SMOKE.`
	Msgs[85] = `NOW YOU'VE REALLY DONE IT. I'M OUT OF ORANGE SMOKE. YOU DON'T EXPECT ME TO DO A DECENT REINCARNATION WITHOUT ANY ORANGE SMOKE, DO YOU?`
	Msgs[86] = `OKAY, IF YOU'RE SO SMART, DO IT YOURSELF. I'M LEAVING!`
	Msgs[90] = `>>> MESSAGES 81 THRU 90 ARE RESERVED FOR "OBITUARIES". <<<`
	Msgs[91] = `SORRY, BUT I NO LONGER SEEM TO REMEMBER HOW IT WAS YOU GOT HERE.`
	Msgs[92] = `YOU CAN'T CARRY ANYTHING MORE. YOU'LL HAVE TO DROP SOMETHING FIRST.`
	Msgs[93] = `YOU CAN'T GO THROUGH A LOCKED STEEL GRATE!`
	Msgs[94] = `I BELIEVE WHAT YOU WANT IS RIGHT HERE WITH YOU.`
	Msgs[95] = `YOU DON'T FIT THROUGH A TWO-INCH SLIT!`
	Msgs[96] = `I RESPECTFULLY SUGGEST YOU GO ACROSS THE BRIDGE INSTEAD OF JUMPING.`
	Msgs[97] = `THERE IS NO WAY ACROSS THE FISSURE.`
	Msgs[98] = `YOU'RE NOT CARRYING ANYTHING.`
	Msgs[99] = `YOU ARE CURRENTLY HOLDING THE FOLLOWING:`
	Msgs[100] = `IT'S NOT HUNGRY (IT'S MERELY PININ' FOR THE FJORDS). BESIDES, YOU HAVE NO BIRD SEED.`
	Msgs[101] = `THE SNAKE HAS NOW DEVOURED YOUR BIRD.`
	Msgs[102] = `THERE'S NOTHING HERE IT WANTS TO EAT (EXCEPT PERHAPS YOU).`
	Msgs[103] = `YOU FOOL, DWARVES EAT ONLY COAL. NOW YOU'VE MADE HIM *REALLY* MAD!!`
	Msgs[104] = `YOU HAVE NOTHING IN WHICH TO CARRY IT.`
	Msgs[105] = `YOUR BOTTLE IS ALREADY FULL.`
	Msgs[106] = `THERE IS NOTHING HERE WITH WHICH TO FILL THE BOTTLE.`
	Msgs[107] = `YOUR BOTTLE IS NOW FULL OF WATER.`
	Msgs[108] = `YOUR BOTTLE IS NOW FULL OF OIL.`
	Msgs[109] = `YOU CAN'T FILL THAT.`
	Msgs[110] = `DON'T BE RIDICULOUS!`
	Msgs[111] = `THE DOOR IS EXTREMELY RUSTY AND REFUSES TO OPEN.`
	Msgs[112] = `THE PLANT INDIGNANTLY SHAKES THE OIL OFF ITS LEAVES AND ASKS, "WATER?"`
	Msgs[113] = `THE HINGES ARE QUITE THOROUGHLY RUSTED NOW AND WON'T BUDGE.`
	Msgs[114] = `THE OIL HAS FREED UP THE HINGES SO THAT THE DOOR WILL NOW MOVE, ALTHOUGH IT REQUIRES SOME EFFORT.`
	Msgs[115] = `THE PLANT HAS EXCEPTIONALLY DEEP ROOTS AND CANNOT BE PULLED FREE.`
	Msgs[116] = `THE DWARVES' KNIVES VANISH AS THEY STRIKE THE WALLS OF THE CAVE.`
	Msgs[117] = `SOMETHING YOU'RE CARRYING WON'T FIT THROUGH THE TUNNEL WITH YOU. YOU'D BEST TAKE INVENTORY AND DROP SOMETHING.`
	Msgs[118] = `YOU CAN'T FIT THIS FIVE-FOOT CLAM THROUGH THAT LITTLE PASSAGE!`
	Msgs[119] = `YOU CAN'T FIT THIS FIVE-FOOT OYSTER THROUGH THAT LITTLE PASSAGE!`
	Msgs[120] = `I ADVISE YOU TO PUT DOWN THE CLAM BEFORE OPENING IT. >STRAIN!<`
	Msgs[121] = `I ADVISE YOU TO PUT DOWN THE OYSTER BEFORE OPENING IT. >WRENCH!<`
	Msgs[122] = `YOU DON'T HAVE ANYTHING STRONG ENOUGH TO OPEN THE CLAM.`
	Msgs[123] = `YOU DON'T HAVE ANYTHING STRONG ENOUGH TO OPEN THE OYSTER.`
	Msgs[124] = `A GLISTENING PEARL FALLS OUT OF THE CLAM AND ROLLS AWAY. GOODNESS, THIS MUST REALLY BE AN OYSTER. (I NEVER WAS VERY GOOD AT IDENTIFYING BIVALVES.. WHATEVER IT IS, IT HAS NOW SNAPPED SHUT AGAIN.`
	Msgs[125] = `THE OYSTER CREAKS OPEN, REVEALING NOTHING BUT OYSTER INSIDE. IT PROMPTLY SNAPS SHUT AGAIN.`
	Msgs[126] = `YOU HAVE CRAWLED AROUND IN SOME LITTLE HOLES AND FOUND YOUR WAY BLOCKED BY A RECENT CAVE-IN. YOU ARE NOW BACK IN THE MAIN PASSAGE.`
	Msgs[127] = `THERE ARE FAINT RUSTLING NOISES FROM THE DARKNESS BEHIND YOU.`
	Msgs[128] = `OUT FROM THE SHADOWS BEHIND YOU POUNCES A BEARDED PIRATE. "HAR, HAR," HE CHORTLES, "I'LL JUST TAKE ALL THIS BOOTY AND HIDE IT AWAY WITH ME CHEST DEEP IN THE MAZE!. HE SNATCHES YOUR TREASURE AND VANISHES INTO THE GLOOM.`
	Msgs[129] = `A SEPULCHRAL VOICE REVERBERATING THROUGH THE CAVE, SAYS, "CAVE CLOSING SOON. ALL ADVENTURERS EXIT IMMEDIATELY THROUGH MAIN OFFICE."`
	Msgs[130] = `A MYSTERIOUS RECORDED VOICE GROANS INTO LIFE AND ANNOUNCES: . "THIS EXIT IS CLOSED. PLEASE LEAVE VIA MAIN OFFICE."`
	Msgs[131] = `IT LOOKS AS THOUGH YOU'RE DEAD. WELL, SEEING AS HOW IT'S SO CLOSE TO CLOSING TIME ANYWAY, I THINK WE'LL JUST CALL IT A DAY.`
	Msgs[132] = `THE SEPULCHRAL VOICE ENTONES, "THE CAVE IS NOW CLOSED.. AS THE ECHOES FADE, THERE IS A BLINDING FLASH OF LIGHT (AND A SMALL PUFF OF ORANGE SMOKE). . . . AS YOUR EYES REFOCUS, YOU LOOK AROUND AND FIND...`
	Msgs[133] = `THERE IS A LOUD EXPLOSION, AND A TWENTY-FOOT HOLE APPEARS IN THE FAR WALL, BURYING THE DWARVES IN THE RUBBLE. YOU MARCH THROUGH THE HOLE AND FIND YOURSELF IN THE MAIN OFFICE, WHERE A CHEERING BAND OF FRIENDLY ELVES CARRY THE CONQUERING ADVENTURER OFF INTO THE SUNSET.`
	Msgs[134] = `THERE IS A LOUD EXPLOSION, AND A TWENTY-FOOT HOLE APPEARS IN THE FAR WALL, BURYING THE SNAKES IN THE RUBBLE. A RIVER OF MOLTEN LAVA POURS IN THROUGH THE HOLE, DESTROYING EVERYTHING IN ITS PATH, INCLUDING YOU!`
	Msgs[135] = `THERE IS A LOUD EXPLOSION, AND YOU ARE SUDDENLY SPLASHED ACROSS THE WALLS OF THE ROOM.`
	Msgs[136] = `THE RESULTING RUCKUS HAS AWAKENED THE DWARVES. THERE ARE NOW SEVERAL THREATENING LITTLE DWARVES IN THE ROOM WITH YOU. MOST OF THEM THROW KNIVES AT YOU! ALL OF THEM GET YOU!`
	Msgs[137] = `OH, LEAVE THE POOR UNHAPPY BIRD ALONE.`
	Msgs[138] = `I DARESAY WHATEVER YOU WANT IS AROUND HERE SOMEWHERE.`
	Msgs[139] = `I DON'T KNOW THE WORD "STOP". USE "QUIT" IF YOU WANT TO GIVE UP.`
	Msgs[140] = `YOU CAN'T GET THERE FROM HERE.`
	Msgs[141] = `YOU ARE BEING FOLLOWED BY A VERY LARGE, TAME BEAR.`
	Msgs[142] = `IF YOU WANT TO END YOUR ADVENTURE EARLY, SAY "QUIT". TO SUSPEND YOUR ADVENTURE SUCH THAT YOU CAN CONTINUE LATER, SAY "SUSPEND" (OR "PAUSE" OR "SAVE"). TO SEE WHAT HOURS THE CAVE IS NORMALLY OPEN, SAY "HOURS". TO SEE HOW WELL YOU'RE DOING, SAY "SCORE". TO GET FULL CREDIT FOR A TREASURE, YOU MUST HAVE LEFT IT SAFELY IN THE BUILDING, THOUGH YOU GET PARTIAL CREDIT JUST FOR LOCATING IT. YOU LOSE POINTS FOR GETTING KILLED, OR FOR QUITTING, THOUGH THE FORMER COSTS YOU MORE. THERE ARE ALSO POINTS BASED ON HOW MUCH (IF ANY) OF THE CAVE YOU'VE MANAGED TO EXPLORE; IN PARTICULAR, THERE IS A LARGE BONUS JUST FOR GETTING IN (TO DISTINGUISH THE BEGINNERS FROM THE REST OF THE PACK), AND THERE ARE OTHER WAYS TO DETERMINE WHETHER YOU'VE BEEN THROUGH SOME OF THE MORE HARROWING SECTIONS. IF YOU THINK YOU'VE FOUND ALL THE TREASURES, JUST KEEP EXPLORING FOR A WHILE. IF NOTHING INTERESTING HAPPENS, YOU HAVEN'T FOUND THEM ALL YET. IF SOMETHING INTERESTING *DOES* HAPPEN, IT MEANS YOU'RE GETTING A BONUS AND HAVE AN OPPORTUNITY TO GARNER MANY MORE POINTS IN THE MASTER'S SECTION. I MAY OCCASIONALLY OFFER HINTS IF YOU SEEM TO BE HAVING TROUBLE. IF I DO, I'LL WARN YOU IN ADVANCE HOW MUCH IT WILL AFFECT YOUR SCORE TO ACCEPT THE HINTS. FINALLY, TO SAVE PAPER, YOU MAY SPECIFY "BRIEF", WHICH TELLS ME NEVER TO REPEAT THE FULL DESCRIPTION OF A PLACE UNLESS YOU EXPLICITLY ASK ME TO.`
	Msgs[143] = `DO YOU INDEED WISH TO QUIT NOW?`
	Msgs[144] = `THERE IS NOTHING HERE WITH WHICH TO FILL THE VASE.`
	Msgs[145] = `THE SUDDEN CHANGE IN TEMPERATURE HAS DELICATELY SHATTERED THE VASE.`
	Msgs[146] = `IT IS BEYOND YOUR POWER TO DO THAT.`
	Msgs[147] = `I DON'T KNOW HOW.`
	Msgs[148] = `IT IS TOO FAR UP FOR YOU TO REACH.`
	Msgs[149] = `YOU KILLED A LITTLE DWARF. THE BODY VANISHES IN A CLOUD OF GREASY BLACK SMOKE.`
	Msgs[150] = `THE SHELL IS VERY STRONG AND IS IMPERVIOUS TO ATTACK.`
	Msgs[151] = `WHAT'S THE MATTER, CAN'T YOU READ. NOW YOU'D BEST START OVER.`
	Msgs[152] = `THE AXE BOUNCES HARMLESSLY OFF THE DRAGON'S THICK SCALES.`
	Msgs[153] = `THE DRAGON LOOKS RATHER NASTY. YOU'D BEST NOT TRY TO GET BY.`
	Msgs[154] = `THE LITTLE BIRD ATTACKS THE GREEN DRAGON, AND IN AN ASTOUNDING FLURRY GETS BURNT TO A CINDER. THE ASHES BLOW AWAY.`
	Msgs[155] = `ON WHAT?`
	Msgs[156] = `OKAY, FROM NOW ON I'LL ONLY DESCRIBE A PLACE IN FULL THE FIRST TIME YOU COME TO IT. TO GET THE FULL DESCRIPTION, SAY "LOOK".`
	Msgs[157] = `TROLLS ARE CLOSE RELATIVES WITH THE ROCKS AND HAVE SKIN AS TOUGH AS THAT OF A RHINOCEROS. THE TROLL FENDS OFF YOUR BLOWS EFFORTLESSLY.`
	Msgs[158] = `THE TROLL DEFTLY CATCHES THE AXE, EXAMINES IT CAREFULLY, AND TOSSES IT BACK, DECLARING, "GOOD WORKMANSHIP, BUT IT'S NOT VALUABLE ENOUGH."`
	Msgs[159] = `THE TROLL CATCHES YOUR TREASURE AND SCURRIES AWAY OUT OF SIGHT.`
	Msgs[160] = `THE TROLL REFUSES TO LET YOU CROSS.`
	Msgs[161] = `THERE IS NO LONGER ANY WAY ACROSS THE CHASM.`
	Msgs[162] = `JUST AS YOU REACH THE OTHER SIDE, THE BRIDGE BUCKLES BENEATH THE WEIGHT OF THE BEAR, WHICH WAS STILL FOLLOWING YOU AROUND. YOU SCRABBLE DESPERATELY FOR SUPPORT, BUT AS THE BRIDGE COLLAPSES YOU STUMBLE BACK AND FALL INTO THE CHASM.`
	Msgs[163] = `THE BEAR LUMBERS TOWARD THE TROLL, WHO LETS OUT A STARTLED SHRIEK AND SCURRIES AWAY. THE BEAR SOON GIVES UP THE PURSUIT AND WANDERS BACK.`
	Msgs[164] = `THE AXE MISSES AND LANDS NEAR THE BEAR WHERE YOU CAN'T GET AT IT.`
	Msgs[165] = `WITH WHAT. YOUR BARE HANDS. AGAINST *HIS* BEAR HANDS??`
	Msgs[166] = `THE BEAR IS CONFUSED; HE ONLY WANTS TO BE YOUR FRIEND.`
	Msgs[167] = `FOR CRYING OUT LOUD, THE POOR THING IS ALREADY DEAD!`
	Msgs[168] = `THE BEAR EAGERLY WOLFS DOWN YOUR FOOD, AFTER WHICH HE SEEMS TO CALM DOWN CONSIDERABLY AND EVEN BECOMES RATHER FRIENDLY.`
	Msgs[169] = `THE BEAR IS STILL CHAINED TO THE WALL.`
	Msgs[170] = `THE CHAIN IS STILL LOCKED.`
	Msgs[171] = `THE CHAIN IS NOW UNLOCKED.`
	Msgs[172] = `THE CHAIN IS NOW LOCKED.`
	Msgs[173] = `THERE IS NOTHING HERE TO WHICH THE CHAIN CAN BE LOCKED.`
	Msgs[174] = `THERE IS NOTHING HERE TO EAT.`
	Msgs[175] = `DO YOU WANT THE HINT?`
	Msgs[176] = `DO YOU NEED HELP GETTING OUT OF THE MAZE?`
	Msgs[177] = `YOU CAN MAKE THE PASSAGES LOOK LESS ALIKE BY DROPPING THINGS.`
	Msgs[178] = `ARE YOU TRYING TO EXPLORE BEYOND THE PLOVER ROOM?`
	Msgs[179] = `THERE IS A WAY TO EXPLORE THAT REGION WITHOUT HAVING TO WORRY ABOUT FALLING INTO A PIT. NONE OF THE OBJECTS AVAILABLE IS IMMEDIATELY USEFUL IN DISCOVERING THE SECRET.`
	Msgs[180] = `DO YOU NEED HELP GETTING OUT OF HERE?`
	Msgs[181] = `DON'T GO WEST.`
	Msgs[182] = `GLUTTONY IS NOT ONE OF THE TROLL'S VICES. AVARICE, HOWEVER, IS.`
	Msgs[183] = `YOUR LAMP IS GETTING DIM. YOU'D BEST START WRAPPING THIS UP, UNLESS YOU CAN FIND SOME FRESH BATTERIES. I SEEM TO RECALL THERE'S A VENDING MACHINE IN THE MAZE. BRING SOME COINS WITH YOU.`
	Msgs[184] = `YOUR LAMP HAS RUN OUT OF POWER.`
	Msgs[185] = `THERE'S NOT MUCH POINT IN WANDERING AROUND OUT HERE, AND YOU CAN'T EXPLORE THE CAVE WITHOUT A LAMP. SO LET'S JUST CALL IT A DAY.`
	Msgs[186] = `THERE ARE FAINT RUSTLING NOISES FROM THE DARKNESS BEHIND YOU. AS YOU TURN TOWARD THEM, THE BEAM OF YOUR LAMP FALLS ACROSS A BEARDED PIRATE. HE IS CARRYING A LARGE CHEST. "SHIVER ME TIMBERS!" HE CRIES, "I'VE BEEN SPOTTED. I'D BEST HIE MESELF OFF TO THE MAZE TO HIDE ME CHEST!" WITH THAT, HE VANISHES INTO THE GLOOM.`
	Msgs[187] = `YOUR LAMP IS GETTING DIM. YOU'D BEST GO BACK FOR THOSE BATTERIES.`
	Msgs[188] = `YOUR LAMP IS GETTING DIM. I'M TAKING THE LIBERTY OF REPLACING THE BATTERIES.`
	Msgs[189] = `YOUR LAMP IS GETTING DIM, AND YOU'RE OUT OF SPARE BATTERIES. YOU'D BEST START WRAPPING THIS UP.`
	Msgs[190] = `I'M AFRAID THE MAGAZINE IS WRITTEN IN DWARVISH.`
	Msgs[191] = `"THIS IS NOT THE MAZE WHERE THE PIRATE LEAVES HIS TREASURE CHEST."`
	Msgs[192] = `HMMM, THIS LOOKS LIKE A CLUE, WHICH MEANS IT'LL COST YOU 10 POINTS TO READ IT. SHOULD I GO AHEAD AND READ IT ANYWAY?`
	Msgs[193] = `IT SAYS, "THERE IS SOMETHING STRANGE ABOUT THIS PLACE, SUCH THAT ONE OF THE WORDS I'VE ALWAYS KNOWN NOW HAS A NEW EFFECT."`
	Msgs[194] = `IT SAYS THE SAME THING IT DID BEFORE.`
	Msgs[195] = `I'M AFRAID I DON'T UNDERSTAND.`
	Msgs[196] = `"CONGRATULATIONS ON BRINGING LIGHT INTO THE DARK-ROOM!"`
	Msgs[197] = `YOU STRIKE THE MIRROR A RESOUNDING BLOW, WHEREUPON IT SHATTERS INTO A MYRIAD TINY FRAGMENTS.`
	Msgs[198] = `YOU HAVE TAKEN THE VASE AND HURLED IT DELICATELY TO THE GROUND.`
	Msgs[199] = `YOU PROD THE NEAREST DWARF, WHO WAKES UP GRUMPILY, TAKES ONE LOOK AT YOU, CURSES, AND GRABS FOR HIS AXE.`
	Msgs[200] = `IS THIS ACCEPTABLE? THERE'S NO POINT IN SUSPENDING A DEMONSTRATION GAME.`
}

func LoadObjectLoc() {
    // section 7 - Object Locations
    // -1 = immovable objects, 2nd number = alternate location?
	Objects[1001].Location = 3
	Objects[1002].Location = 3
	Objects[1003].Location = 8
	Objects[1003].AltLocation = 9
	Objects[1004].Location = 10
	Objects[1005].Location = 11
	Objects[1006].Location = 0
	Objects[1007].Location = 14
	Objects[1007].AltLocation = 15
	Objects[1008].Location = 13
	Objects[1009].Location = 94
	Objects[1009].Immovable = true
	Objects[1010].Location = 96
	Objects[1011].Location = 19
	Objects[1011].Immovable = true
	Objects[1012].Location = 17
	Objects[1012].AltLocation = 27
	Objects[1013].Location = 101
	Objects[1013].Immovable = true
	Objects[1014].Location = 103
	Objects[1015].Location = 0
	Objects[1016].Location = 106
	Objects[1017].Location = 0
	Objects[1017].Immovable = true
	Objects[1018].Location = 0
	Objects[1019].Location = 3
	Objects[1020].Location = 3
	Objects[1021].Location = 0
	Objects[1022].Location = 0
	Objects[1023].Location = 109
	Objects[1023].Immovable = true
	Objects[1024].Location = 25
	Objects[1024].Immovable = true
	Objects[1025].Location = 23
	Objects[1025].AltLocation = 67
	Objects[1026].Location = 111
	Objects[1026].Immovable = true
	Objects[1027].Location = 35
	Objects[1027].AltLocation = 110
	Objects[1028].Location = 0
	Objects[1029].Location = 97
	Objects[1029].Immovable = true
	Objects[1030].Location = 0
	Objects[1030].Immovable = true
	Objects[1031].Location = 119
	Objects[1031].AltLocation = 121
	Objects[1032].Location = 117
	Objects[1032].AltLocation = 122
	Objects[1033].Location = 117
	Objects[1033].AltLocation = 122
	Objects[1034].Location = 0
	Objects[1034].AltLocation = 0
	Objects[1035].Location = 130
	Objects[1035].Immovable = true
	Objects[1036].Location = 0
	Objects[1036].Immovable = true
	Objects[1037].Location = 126
	Objects[1037].Immovable = true
	Objects[1038].Location = 140
	Objects[1038].Immovable = true
	Objects[1039].Location = 0
	Objects[1040].Location = 96
	Objects[1040].Immovable = true
	Objects[1050].Location = 18
	Objects[1051].Location = 27
	Objects[1052].Location = 28
	Objects[1053].Location = 29
	Objects[1054].Location = 30
	Objects[1055].Location = 0
	Objects[1056].Location = 92
	Objects[1057].Location = 95
	Objects[1058].Location = 97
	Objects[1059].Location = 100
	Objects[1060].Location = 101
	Objects[1061].Location = 0
	Objects[1062].Location = 119
	Objects[1062].AltLocation = 121
	Objects[1063].Location = 127
	Objects[1064].Location = 130
	Objects[1064].Immovable = true
}

/*

// section 8 -- action defaults, "proper" definition for each action
1 24
2 29
3 0
4 33
5 0
6 33
7 38
8 38
9 42
10 14
11 43
12 110
13 29
14 110
15 73
16 75
17 29
18 13
19 59
20 59
21 174
22 109
23 67
24 13
25 147
26 155
27 195
28 146
29 110
30 13
31 13


// section 9 = liquid assets?
0 1 2 3 4 5 6 7 8 9 10
0 100 115 116 126
2 1 3 4 7 38 95 113 24
1 24
3 46 47 48 54 56 58 82 85 86
3 122 123 124 125 126 127 128 129 130
4 8
5 13
6 19
7 42 43 44 45 46 47 48 49 50 51
7 52 53 54 55 56 80 81 82 86 87
8 99 100 101
9 108

*/

// section 10 = class messages = player rank
func GetScore(s int) string {
	if s <= 35 {
		return `YOU ARE OBVIOUSLY A RANK AMATEUR. BETTER LUCK NEXT TIME.`
	}
	if s <= 100 {
		return `YOUR SCORE QUALIFIES YOU AS A NOVICE CLASS ADVENTURER.`
	}
	if s <= 130 {
		return `YOU HAVE ACHIEVED THE RATING: "EXPERIENCED ADVENTURER".`
	}
	if s <= 200 {
		return `YOU MAY NOW CONSIDER YOURSELF A "SEASONED ADVENTURER".`
	}
	if s <= 250 {
		return `YOU HAVE REACHED "JUNIOR MASTER" STATUS.`
	}
	if s <= 300 {
		return `YOUR SCORE PUTS YOU IN MASTER ADVENTURER CLASS C.`
	}
	if s <= 330 {
		return `YOUR SCORE PUTS YOU IN MASTER ADVENTURER CLASS B.`
	}
	if s <= 349 {
		return `YOUR SCORE PUTS YOU IN MASTER ADVENTURER CLASS A.`
	}
	if s <= 9999 {
		return `ALL OF ADVENTUREDOM GIVES TRIBUTE TO YOU, ADVENTURER GRANDMASTER!`
	}
	return ""
}

/*
// section 11 == hints.
var Hints = make(map[int][]int)
2 9999 10 0 0
3 9999 5 0 0
4 4 2 62 63
5 5 2 18 19
6 8 2 20 21
7 75 4 176 177
8 25 5 178 179
9 20 3 180 181

// probably never ever use this
// section 12 = magic messages, identical to section 6
var MagicMsg = make(map[int]string)

MagicMsg[1] = `A LARGE CLOUD OF GREEN SMOKE APPEARS IN FRONT OF YOU. IT CLEARS AWAY TO REVEAL A TALL WIZARD, CLOTHED IN GREY. HE FIXES YOU WITH A STEELY GLARE AND DECLARES, "THIS ADVENTURE HAS LASTED TOO LONG.. WITH THAT HE MAKES A SINGLE PASS OVER YOU WITH HIS HANDS, AND EVERYTHING AROUND YOU FADES AWAY INTO A GREY NOTHINGNESS.`
MagicMsg[2] = `EVEN WIZARDS HAVE TO WAIT LONGER THAN THAT!`
MagicMsg[3] = `I'M TERRIBLY SORRY, BUT COLOSSAL CAVE IS CLOSED. OUR HOURS ARE:`
MagicMsg[4] = `ONLY WIZARDS ARE PERMITTED WITHIN THE CAVE RIGHT NOW.`
MagicMsg[5] = `WE DO ALLOW VISITORS TO MAKE SHORT EXPLORATIONS DURING OUR OFF HOURS. WOULD YOU LIKE TO DO THAT?`
MagicMsg[6] = `COLOSSAL CAVE IS OPEN TO REGULAR ADVENTURERS AT THE FOLLOWING HOURS:`
MagicMsg[7] = `VERY WELL.`
MagicMsg[8] = `ONLY A WIZARD MAY CONTINUE AN ADVENTURE THIS SOON.`
MagicMsg[9] = `I SUGGEST YOU RESUME YOUR ADVENTURE AT A LATER TIME.`
MagicMsg[10] = `DO YOU WISH TO SEE THE HOURS?`
MagicMsg[11] = `DO YOU WISH TO CHANGE THE HOURS?`
MagicMsg[12] = `NEW MAGIC WORD (NULL TO LEAVE UNCHANGED):`
MagicMsg[13] = `NEW MAGIC NUMBER (NULL TO LEAVE UNCHANGED):`
MagicMsg[14] = `DO YOU WISH TO CHANGE THE MESSAGE OF THE DAY?`
MagicMsg[15] = `OKAY. YOU CAN SAVE THIS VERSION NOW.`
MagicMsg[16] = `ARE YOU A WIZARD?`
MagicMsg[17] = `PROVE IT. SAY THE MAGIC WORD!`
MagicMsg[18] = `THAT IS NOT WHAT I THOUGHT IT WAS. DO YOU KNOW WHAT I THOUGHT IT WAS?`
MagicMsg[19] = `OH DEAR, YOU REALLY *ARE* A WIZARD. SORRY TO HAVE BOTHERED YOU . . .`
MagicMsg[20] = `FOO, YOU ARE NOTHING BUT A CHARLATAN!`
MagicMsg[21] = `NEW HOURS SPECIFIED BY DEFINING "PRIME TIME". GIVE ONLY THE HOUR (E.G. 14, NOT 14:00 OR 2PM). ENTER A NEGATIVE NUMBER AFTER LAST PAIR.`
MagicMsg[22] = `NEW HOURS FOR COLOSSAL CAVE:`
MagicMsg[23] = `LIMIT LINES TO 70 CHARS. END WITH NULL LINE.`
MagicMsg[24] = `LINE TOO LONG, RETYPE:`
MagicMsg[25] = `NOT ENOUGH ROOM FOR ANOTHER LINE. ENDING MESSAGE HERE.`
MagicMsg[26] = `DO YOU WISH TO (RE)SCHEDULE THE NEXT HOLIDAY?`
MagicMsg[27] = `TO BEGIN HOW MANY DAYS FROM TODAY?`
MagicMsg[28] = `TO LAST HOW MANY DAYS (ZERO IF NO HOLIDAY)?`
MagicMsg[29] = `TO BE CALLED WHAT (UP TO 20 CHARACTERS)?`
MagicMsg[30] = `TOO SMALL. ASSUMING MINIMUM VALUE (45 MINUTES).`
MagicMsg[31] = `BREAK OUT OF THIS AND SAVE YOUR CORE-IMAGE.`
MagicMsg[32] = `BE SURE TO SAVE YOUR CORE-IMAGE...`
*/
